export type McItem = {
  id: string;
  name: string;
  category: string;
  rarity: number; // 1 = most rare (shown first), higher = more common
};

export function mcItemIconUrl(itemId: string): string {
  const pascal = itemId
    .split("_")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("_");
  return `https://minecraft.wiki/images/Invicon_${pascal}.png`;
}

// Survival-obtainable items only — ordered rarest first (rarity 1) to most common (rarity 9)
export const MC_ITEMS: McItem[] = [
  // ── Rarity 1 — Legendary / Near-unobtainable ──
  { id: "dragon_egg", name: "Dragon Egg", category: "Blocks", rarity: 1 },
  { id: "elytra", name: "Elytra", category: "Armor", rarity: 1 },
  { id: "nether_star", name: "Nether Star", category: "Materials", rarity: 1 },
  { id: "beacon", name: "Beacon", category: "Blocks", rarity: 1 },
  { id: "enchanted_golden_apple", name: "Enchanted Golden Apple", category: "Food", rarity: 1 },
  { id: "end_crystal", name: "End Crystal", category: "Combat", rarity: 1 },

  // ── Rarity 2 — Very rare drops / hard to obtain ──
  { id: "netherite_ingot", name: "Netherite Ingot", category: "Materials", rarity: 2 },
  { id: "netherite_scrap", name: "Netherite Scrap", category: "Materials", rarity: 2 },
  { id: "ancient_debris", name: "Ancient Debris", category: "Materials", rarity: 2 },
  { id: "netherite_block", name: "Block of Netherite", category: "Blocks", rarity: 2 },
  { id: "netherite_upgrade_smithing_template", name: "Netherite Upgrade Template", category: "Smithing", rarity: 2 },
  { id: "netherite_sword", name: "Netherite Sword", category: "Weapons", rarity: 2 },
  { id: "netherite_pickaxe", name: "Netherite Pickaxe", category: "Tools", rarity: 2 },
  { id: "netherite_axe", name: "Netherite Axe", category: "Tools", rarity: 2 },
  { id: "netherite_shovel", name: "Netherite Shovel", category: "Tools", rarity: 2 },
  { id: "netherite_hoe", name: "Netherite Hoe", category: "Tools", rarity: 2 },
  { id: "netherite_helmet", name: "Netherite Helmet", category: "Armor", rarity: 2 },
  { id: "netherite_chestplate", name: "Netherite Chestplate", category: "Armor", rarity: 2 },
  { id: "netherite_leggings", name: "Netherite Leggings", category: "Armor", rarity: 2 },
  { id: "netherite_boots", name: "Netherite Boots", category: "Armor", rarity: 2 },
  { id: "totem_of_undying", name: "Totem of Undying", category: "Combat", rarity: 2 },
  { id: "trident", name: "Trident", category: "Weapons", rarity: 2 },
  { id: "mace", name: "Mace", category: "Weapons", rarity: 2 },
  { id: "heavy_core", name: "Heavy Core", category: "Materials", rarity: 2 },
  { id: "heart_of_the_sea", name: "Heart of the Sea", category: "Ocean", rarity: 2 },
  { id: "conduit", name: "Conduit", category: "Blocks", rarity: 2 },
  { id: "silence_armor_trim_smithing_template", name: "Silence Armor Trim", category: "Smithing", rarity: 2 },
  { id: "spire_armor_trim_smithing_template", name: "Spire Armor Trim", category: "Smithing", rarity: 2 },
  { id: "rib_armor_trim_smithing_template", name: "Rib Armor Trim", category: "Smithing", rarity: 2 },
  { id: "wither_skeleton_skull", name: "Wither Skeleton Skull", category: "Combat", rarity: 2 },
  { id: "reinforced_deepslate", name: "Reinforced Deepslate", category: "Blocks", rarity: 2 },
  { id: "music_disc_pigstep", name: "Music Disc (Pigstep)", category: "Music", rarity: 2 },
  { id: "music_disc_otherside", name: "Music Disc (Otherside)", category: "Music", rarity: 2 },
  { id: "music_disc_relic", name: "Music Disc (Relic)", category: "Music", rarity: 2 },
  { id: "music_disc_precipice", name: "Music Disc (Precipice)", category: "Music", rarity: 2 },
  { id: "music_disc_creator", name: "Music Disc (Creator)", category: "Music", rarity: 2 },

  // ── Rarity 3 — Rare boss/structure loot ──
  { id: "shulker_shell", name: "Shulker Shell", category: "Materials", rarity: 3 },
  { id: "shulker_box", name: "Shulker Box", category: "Blocks", rarity: 3 },
  { id: "white_shulker_box", name: "White Shulker Box", category: "Blocks", rarity: 3 },
  { id: "orange_shulker_box", name: "Orange Shulker Box", category: "Blocks", rarity: 3 },
  { id: "magenta_shulker_box", name: "Magenta Shulker Box", category: "Blocks", rarity: 3 },
  { id: "light_blue_shulker_box", name: "Light Blue Shulker Box", category: "Blocks", rarity: 3 },
  { id: "yellow_shulker_box", name: "Yellow Shulker Box", category: "Blocks", rarity: 3 },
  { id: "lime_shulker_box", name: "Lime Shulker Box", category: "Blocks", rarity: 3 },
  { id: "pink_shulker_box", name: "Pink Shulker Box", category: "Blocks", rarity: 3 },
  { id: "gray_shulker_box", name: "Gray Shulker Box", category: "Blocks", rarity: 3 },
  { id: "light_gray_shulker_box", name: "Light Gray Shulker Box", category: "Blocks", rarity: 3 },
  { id: "cyan_shulker_box", name: "Cyan Shulker Box", category: "Blocks", rarity: 3 },
  { id: "purple_shulker_box", name: "Purple Shulker Box", category: "Blocks", rarity: 3 },
  { id: "blue_shulker_box", name: "Blue Shulker Box", category: "Blocks", rarity: 3 },
  { id: "brown_shulker_box", name: "Brown Shulker Box", category: "Blocks", rarity: 3 },
  { id: "green_shulker_box", name: "Green Shulker Box", category: "Blocks", rarity: 3 },
  { id: "red_shulker_box", name: "Red Shulker Box", category: "Blocks", rarity: 3 },
  { id: "black_shulker_box", name: "Black Shulker Box", category: "Blocks", rarity: 3 },
  { id: "dragon_breath", name: "Dragon's Breath", category: "Materials", rarity: 3 },
  { id: "dragon_head", name: "Dragon Head", category: "Blocks", rarity: 3 },
  { id: "ghast_tear", name: "Ghast Tear", category: "Materials", rarity: 3 },
  { id: "ominous_trial_key", name: "Ominous Trial Key", category: "Combat", rarity: 3 },
  { id: "trial_key", name: "Trial Key", category: "Combat", rarity: 3 },
  { id: "ominous_bottle", name: "Ominous Bottle", category: "Combat", rarity: 3 },
  { id: "enchanted_book", name: "Enchanted Book", category: "Enchanting", rarity: 3 },
  { id: "experience_bottle", name: "Bottle o' Enchanting", category: "Enchanting", rarity: 3 },
  { id: "eye_of_ender", name: "Eye of Ender", category: "Materials", rarity: 3 },
  { id: "golden_apple", name: "Golden Apple", category: "Food", rarity: 3 },
  { id: "recovery_compass", name: "Recovery Compass", category: "Tools", rarity: 3 },
  { id: "coast_armor_trim_smithing_template", name: "Coast Armor Trim", category: "Smithing", rarity: 3 },
  { id: "dune_armor_trim_smithing_template", name: "Dune Armor Trim", category: "Smithing", rarity: 3 },
  { id: "eye_armor_trim_smithing_template", name: "Eye Armor Trim", category: "Smithing", rarity: 3 },
  { id: "host_armor_trim_smithing_template", name: "Host Armor Trim", category: "Smithing", rarity: 3 },
  { id: "raiser_armor_trim_smithing_template", name: "Raiser Armor Trim", category: "Smithing", rarity: 3 },
  { id: "sentry_armor_trim_smithing_template", name: "Sentry Armor Trim", category: "Smithing", rarity: 3 },
  { id: "shaper_armor_trim_smithing_template", name: "Shaper Armor Trim", category: "Smithing", rarity: 3 },
  { id: "snout_armor_trim_smithing_template", name: "Snout Armor Trim", category: "Smithing", rarity: 3 },
  { id: "tide_armor_trim_smithing_template", name: "Tide Armor Trim", category: "Smithing", rarity: 3 },
  { id: "vex_armor_trim_smithing_template", name: "Vex Armor Trim", category: "Smithing", rarity: 3 },
  { id: "ward_armor_trim_smithing_template", name: "Ward Armor Trim", category: "Smithing", rarity: 3 },
  { id: "wayfinder_armor_trim_smithing_template", name: "Wayfinder Armor Trim", category: "Smithing", rarity: 3 },
  { id: "wild_armor_trim_smithing_template", name: "Wild Armor Trim", category: "Smithing", rarity: 3 },
  { id: "bolt_armor_trim_smithing_template", name: "Bolt Armor Trim", category: "Smithing", rarity: 3 },
  { id: "flow_armor_trim_smithing_template", name: "Flow Armor Trim", category: "Smithing", rarity: 3 },
  { id: "music_disc_13", name: "Music Disc (13)", category: "Music", rarity: 3 },
  { id: "music_disc_cat", name: "Music Disc (Cat)", category: "Music", rarity: 3 },
  { id: "music_disc_blocks", name: "Music Disc (Blocks)", category: "Music", rarity: 3 },
  { id: "music_disc_chirp", name: "Music Disc (Chirp)", category: "Music", rarity: 3 },
  { id: "music_disc_far", name: "Music Disc (Far)", category: "Music", rarity: 3 },
  { id: "music_disc_mall", name: "Music Disc (Mall)", category: "Music", rarity: 3 },
  { id: "music_disc_mellohi", name: "Music Disc (Mellohi)", category: "Music", rarity: 3 },
  { id: "music_disc_stal", name: "Music Disc (Stal)", category: "Music", rarity: 3 },
  { id: "music_disc_strad", name: "Music Disc (Strad)", category: "Music", rarity: 3 },
  { id: "music_disc_ward", name: "Music Disc (Ward)", category: "Music", rarity: 3 },
  { id: "music_disc_11", name: "Music Disc (11)", category: "Music", rarity: 3 },
  { id: "music_disc_wait", name: "Music Disc (Wait)", category: "Music", rarity: 3 },
  { id: "music_disc_5", name: "Music Disc (5)", category: "Music", rarity: 3 },
  { id: "music_disc_creator_music_box", name: "Music Disc (Creator Music Box)", category: "Music", rarity: 3 },
  { id: "disc_fragment_5", name: "Disc Fragment (5)", category: "Music", rarity: 3 },

  // ── Rarity 4 — Uncommon / mob drops & mining ──
  { id: "diamond", name: "Diamond", category: "Materials", rarity: 4 },
  { id: "diamond_block", name: "Block of Diamond", category: "Blocks", rarity: 4 },
  { id: "diamond_sword", name: "Diamond Sword", category: "Weapons", rarity: 4 },
  { id: "diamond_pickaxe", name: "Diamond Pickaxe", category: "Tools", rarity: 4 },
  { id: "diamond_axe", name: "Diamond Axe", category: "Tools", rarity: 4 },
  { id: "diamond_shovel", name: "Diamond Shovel", category: "Tools", rarity: 4 },
  { id: "diamond_hoe", name: "Diamond Hoe", category: "Tools", rarity: 4 },
  { id: "diamond_helmet", name: "Diamond Helmet", category: "Armor", rarity: 4 },
  { id: "diamond_chestplate", name: "Diamond Chestplate", category: "Armor", rarity: 4 },
  { id: "diamond_leggings", name: "Diamond Leggings", category: "Armor", rarity: 4 },
  { id: "diamond_boots", name: "Diamond Boots", category: "Armor", rarity: 4 },
  { id: "diamond_horse_armor", name: "Diamond Horse Armor", category: "Armor", rarity: 4 },
  { id: "emerald", name: "Emerald", category: "Materials", rarity: 4 },
  { id: "emerald_block", name: "Block of Emerald", category: "Blocks", rarity: 4 },
  { id: "ender_pearl", name: "Ender Pearl", category: "Materials", rarity: 4 },
  { id: "blaze_rod", name: "Blaze Rod", category: "Materials", rarity: 4 },
  { id: "blaze_powder", name: "Blaze Powder", category: "Materials", rarity: 4 },
  { id: "magma_cream", name: "Magma Cream", category: "Materials", rarity: 4 },
  { id: "prismarine_crystals", name: "Prismarine Crystals", category: "Ocean", rarity: 4 },
  { id: "prismarine_shard", name: "Prismarine Shard", category: "Ocean", rarity: 4 },
  { id: "nautilus_shell", name: "Nautilus Shell", category: "Ocean", rarity: 4 },
  { id: "phantom_membrane", name: "Phantom Membrane", category: "Materials", rarity: 4 },
  { id: "breeze_rod", name: "Breeze Rod", category: "Materials", rarity: 4 },
  { id: "wind_charge", name: "Wind Charge", category: "Combat", rarity: 4 },
  { id: "name_tag", name: "Name Tag", category: "Tools", rarity: 4 },
  { id: "saddle", name: "Saddle", category: "Tools", rarity: 4 },
  { id: "rabbit_foot", name: "Rabbit's Foot", category: "Potions", rarity: 4 },
  { id: "amethyst_shard", name: "Amethyst Shard", category: "Materials", rarity: 4 },
  { id: "amethyst_block", name: "Block of Amethyst", category: "Blocks", rarity: 4 },
  { id: "spyglass", name: "Spyglass", category: "Tools", rarity: 4 },
  { id: "turtle_helmet", name: "Turtle Shell", category: "Armor", rarity: 4 },
  { id: "scute", name: "Scute", category: "Materials", rarity: 4 },
  { id: "armadillo_scute", name: "Armadillo Scute", category: "Materials", rarity: 4 },
  { id: "wolf_armor", name: "Wolf Armor", category: "Armor", rarity: 4 },
  { id: "glow_ink_sac", name: "Glow Ink Sac", category: "Materials", rarity: 4 },
  { id: "lead", name: "Lead", category: "Tools", rarity: 4 },
  { id: "crossbow", name: "Crossbow", category: "Weapons", rarity: 4 },
  { id: "golden_carrot", name: "Golden Carrot", category: "Food", rarity: 4 },
  { id: "fermented_spider_eye", name: "Fermented Spider Eye", category: "Potions", rarity: 4 },
  { id: "lingering_potion", name: "Lingering Potion", category: "Potions", rarity: 4 },
  { id: "popped_chorus_fruit", name: "Popped Chorus Fruit", category: "Materials", rarity: 4 },
  { id: "chorus_fruit", name: "Chorus Fruit", category: "Food", rarity: 4 },

  // ── Rarity 5 — Moderate / crafted from uncommon ──
  { id: "gold_ingot", name: "Gold Ingot", category: "Materials", rarity: 5 },
  { id: "gold_nugget", name: "Gold Nugget", category: "Materials", rarity: 5 },
  { id: "gold_block", name: "Block of Gold", category: "Blocks", rarity: 5 },
  { id: "raw_gold", name: "Raw Gold", category: "Materials", rarity: 5 },
  { id: "raw_gold_block", name: "Raw Gold Block", category: "Blocks", rarity: 5 },
  { id: "golden_sword", name: "Golden Sword", category: "Weapons", rarity: 5 },
  { id: "golden_pickaxe", name: "Golden Pickaxe", category: "Tools", rarity: 5 },
  { id: "golden_axe", name: "Golden Axe", category: "Tools", rarity: 5 },
  { id: "golden_shovel", name: "Golden Shovel", category: "Tools", rarity: 5 },
  { id: "golden_hoe", name: "Golden Hoe", category: "Tools", rarity: 5 },
  { id: "golden_helmet", name: "Golden Helmet", category: "Armor", rarity: 5 },
  { id: "golden_chestplate", name: "Golden Chestplate", category: "Armor", rarity: 5 },
  { id: "golden_leggings", name: "Golden Leggings", category: "Armor", rarity: 5 },
  { id: "golden_boots", name: "Golden Boots", category: "Armor", rarity: 5 },
  { id: "golden_horse_armor", name: "Golden Horse Armor", category: "Armor", rarity: 5 },
  { id: "lapis_lazuli", name: "Lapis Lazuli", category: "Materials", rarity: 5 },
  { id: "lapis_block", name: "Lapis Lazuli Block", category: "Blocks", rarity: 5 },
  { id: "quartz", name: "Nether Quartz", category: "Materials", rarity: 5 },
  { id: "quartz_block", name: "Block of Quartz", category: "Blocks", rarity: 5 },
  { id: "redstone", name: "Redstone Dust", category: "Materials", rarity: 5 },
  { id: "redstone_block", name: "Block of Redstone", category: "Blocks", rarity: 5 },
  { id: "gilded_blackstone", name: "Gilded Blackstone", category: "Blocks", rarity: 5 },
  { id: "nether_wart", name: "Nether Wart", category: "Materials", rarity: 5 },
  { id: "glowstone_dust", name: "Glowstone Dust", category: "Materials", rarity: 5 },
  { id: "glowstone", name: "Glowstone", category: "Blocks", rarity: 5 },
  { id: "sea_lantern", name: "Sea Lantern", category: "Blocks", rarity: 5 },
  { id: "sponge", name: "Sponge", category: "Blocks", rarity: 5 },
  { id: "bow", name: "Bow", category: "Weapons", rarity: 5 },
  { id: "shield", name: "Shield", category: "Combat", rarity: 5 },
  { id: "brush", name: "Brush", category: "Tools", rarity: 5 },
  { id: "decorated_pot", name: "Decorated Pot", category: "Blocks", rarity: 5 },
  { id: "honeycomb", name: "Honeycomb", category: "Materials", rarity: 5 },
  { id: "honey_bottle", name: "Honey Bottle", category: "Food", rarity: 5 },
  { id: "pufferfish", name: "Pufferfish", category: "Potions", rarity: 5 },
  { id: "slimeball", name: "Slimeball", category: "Materials", rarity: 5 },
  { id: "slime_block", name: "Slime Block", category: "Blocks", rarity: 5 },
  { id: "magma_block", name: "Magma Block", category: "Blocks", rarity: 5 },
  { id: "obsidian", name: "Obsidian", category: "Blocks", rarity: 5 },
  { id: "crying_obsidian", name: "Crying Obsidian", category: "Blocks", rarity: 5 },
  { id: "ink_sac", name: "Ink Sac", category: "Materials", rarity: 5 },
  { id: "gunpowder", name: "Gunpowder", category: "Materials", rarity: 5 },
  { id: "spider_eye", name: "Spider Eye", category: "Materials", rarity: 5 },
  { id: "string", name: "String", category: "Materials", rarity: 5 },
  { id: "glistering_melon_slice", name: "Glistering Melon Slice", category: "Potions", rarity: 5 },
  { id: "fire_charge", name: "Fire Charge", category: "Combat", rarity: 5 },
  { id: "tnt", name: "TNT", category: "Blocks", rarity: 5 },
  { id: "splash_potion", name: "Splash Potion", category: "Potions", rarity: 5 },
  { id: "potion", name: "Potion", category: "Potions", rarity: 5 },
  { id: "spectral_arrow", name: "Spectral Arrow", category: "Combat", rarity: 5 },
  { id: "tipped_arrow", name: "Tipped Arrow", category: "Combat", rarity: 5 },
  { id: "firework_rocket", name: "Firework Rocket", category: "Misc", rarity: 5 },
  { id: "firework_star", name: "Firework Star", category: "Misc", rarity: 5 },

  // ── Rarity 6 — Craftable / farmable ──
  { id: "iron_ingot", name: "Iron Ingot", category: "Materials", rarity: 6 },
  { id: "iron_nugget", name: "Iron Nugget", category: "Materials", rarity: 6 },
  { id: "iron_block", name: "Block of Iron", category: "Blocks", rarity: 6 },
  { id: "raw_iron", name: "Raw Iron", category: "Materials", rarity: 6 },
  { id: "raw_iron_block", name: "Raw Iron Block", category: "Blocks", rarity: 6 },
  { id: "iron_sword", name: "Iron Sword", category: "Weapons", rarity: 6 },
  { id: "iron_pickaxe", name: "Iron Pickaxe", category: "Tools", rarity: 6 },
  { id: "iron_axe", name: "Iron Axe", category: "Tools", rarity: 6 },
  { id: "iron_shovel", name: "Iron Shovel", category: "Tools", rarity: 6 },
  { id: "iron_hoe", name: "Iron Hoe", category: "Tools", rarity: 6 },
  { id: "iron_helmet", name: "Iron Helmet", category: "Armor", rarity: 6 },
  { id: "iron_chestplate", name: "Iron Chestplate", category: "Armor", rarity: 6 },
  { id: "iron_leggings", name: "Iron Leggings", category: "Armor", rarity: 6 },
  { id: "iron_boots", name: "Iron Boots", category: "Armor", rarity: 6 },
  { id: "iron_horse_armor", name: "Iron Horse Armor", category: "Armor", rarity: 6 },
  { id: "copper_ingot", name: "Copper Ingot", category: "Materials", rarity: 6 },
  { id: "raw_copper", name: "Raw Copper", category: "Materials", rarity: 6 },
  { id: "copper_block", name: "Copper Block", category: "Blocks", rarity: 6 },
  { id: "coal", name: "Coal", category: "Materials", rarity: 6 },
  { id: "charcoal", name: "Charcoal", category: "Materials", rarity: 6 },
  { id: "coal_block", name: "Block of Coal", category: "Blocks", rarity: 6 },
  { id: "nether_brick", name: "Nether Brick", category: "Materials", rarity: 6 },
  { id: "nether_bricks", name: "Nether Bricks", category: "Blocks", rarity: 6 },
  { id: "shroomlight", name: "Shroomlight", category: "Blocks", rarity: 6 },
  { id: "leather", name: "Leather", category: "Materials", rarity: 6 },
  { id: "leather_helmet", name: "Leather Helmet", category: "Armor", rarity: 6 },
  { id: "leather_chestplate", name: "Leather Chestplate", category: "Armor", rarity: 6 },
  { id: "leather_leggings", name: "Leather Leggings", category: "Armor", rarity: 6 },
  { id: "leather_boots", name: "Leather Boots", category: "Armor", rarity: 6 },
  { id: "leather_horse_armor", name: "Leather Horse Armor", category: "Armor", rarity: 6 },
  { id: "bone", name: "Bone", category: "Materials", rarity: 6 },
  { id: "bone_meal", name: "Bone Meal", category: "Materials", rarity: 6 },
  { id: "bone_block", name: "Bone Block", category: "Blocks", rarity: 6 },
  { id: "feather", name: "Feather", category: "Materials", rarity: 6 },
  { id: "flint", name: "Flint", category: "Materials", rarity: 6 },
  { id: "flint_and_steel", name: "Flint and Steel", category: "Tools", rarity: 6 },
  { id: "shears", name: "Shears", category: "Tools", rarity: 6 },
  { id: "fishing_rod", name: "Fishing Rod", category: "Tools", rarity: 6 },
  { id: "bucket", name: "Bucket", category: "Tools", rarity: 6 },
  { id: "water_bucket", name: "Water Bucket", category: "Tools", rarity: 6 },
  { id: "lava_bucket", name: "Lava Bucket", category: "Tools", rarity: 6 },
  { id: "milk_bucket", name: "Milk Bucket", category: "Tools", rarity: 6 },
  { id: "compass", name: "Compass", category: "Tools", rarity: 6 },
  { id: "clock", name: "Clock", category: "Tools", rarity: 6 },
  { id: "map", name: "Map", category: "Tools", rarity: 6 },
  { id: "filled_map", name: "Filled Map", category: "Tools", rarity: 6 },
  { id: "book", name: "Book", category: "Enchanting", rarity: 6 },
  { id: "bookshelf", name: "Bookshelf", category: "Enchanting", rarity: 6 },
  { id: "chiseled_bookshelf", name: "Chiseled Bookshelf", category: "Enchanting", rarity: 6 },
  { id: "grindstone", name: "Grindstone", category: "Enchanting", rarity: 6 },
  { id: "anvil", name: "Anvil", category: "Blocks", rarity: 6 },
  { id: "enchanting_table", name: "Enchanting Table", category: "Blocks", rarity: 6 },
  { id: "brewing_stand", name: "Brewing Stand", category: "Blocks", rarity: 6 },
  { id: "glass_bottle", name: "Glass Bottle", category: "Potions", rarity: 6 },
  { id: "arrow", name: "Arrow", category: "Combat", rarity: 6 },
  { id: "honeycomb_block", name: "Honeycomb Block", category: "Blocks", rarity: 6 },
  { id: "honey_block", name: "Honey Block", category: "Blocks", rarity: 6 },
  { id: "beehive", name: "Beehive", category: "Blocks", rarity: 6 },
  { id: "bee_nest", name: "Bee Nest", category: "Blocks", rarity: 6 },
  { id: "warped_fungus_on_a_stick", name: "Warped Fungus on a Stick", category: "Tools", rarity: 6 },
  { id: "carrot_on_a_stick", name: "Carrot on a Stick", category: "Tools", rarity: 6 },
  { id: "saddle", name: "Saddle (fishing)", category: "Tools", rarity: 6 },
  { id: "dried_kelp", name: "Dried Kelp", category: "Food", rarity: 6 },
  { id: "dried_kelp_block", name: "Dried Kelp Block", category: "Blocks", rarity: 6 },
  { id: "kelp", name: "Kelp", category: "Ocean", rarity: 6 },
  { id: "powder_snow_bucket", name: "Powder Snow Bucket", category: "Tools", rarity: 6 },

  // ── Rarity 7 — Common crafted / abundant ──
  { id: "stone_sword", name: "Stone Sword", category: "Weapons", rarity: 7 },
  { id: "stone_pickaxe", name: "Stone Pickaxe", category: "Tools", rarity: 7 },
  { id: "stone_axe", name: "Stone Axe", category: "Tools", rarity: 7 },
  { id: "stone_shovel", name: "Stone Shovel", category: "Tools", rarity: 7 },
  { id: "stone_hoe", name: "Stone Hoe", category: "Tools", rarity: 7 },
  { id: "wooden_sword", name: "Wooden Sword", category: "Weapons", rarity: 7 },
  { id: "wooden_pickaxe", name: "Wooden Pickaxe", category: "Tools", rarity: 7 },
  { id: "wooden_axe", name: "Wooden Axe", category: "Tools", rarity: 7 },
  { id: "wooden_shovel", name: "Wooden Shovel", category: "Tools", rarity: 7 },
  { id: "wooden_hoe", name: "Wooden Hoe", category: "Tools", rarity: 7 },
  { id: "chest", name: "Chest", category: "Blocks", rarity: 7 },
  { id: "trapped_chest", name: "Trapped Chest", category: "Blocks", rarity: 7 },
  { id: "barrel", name: "Barrel", category: "Blocks", rarity: 7 },
  { id: "ender_chest", name: "Ender Chest", category: "Blocks", rarity: 7 },
  { id: "crafting_table", name: "Crafting Table", category: "Blocks", rarity: 7 },
  { id: "furnace", name: "Furnace", category: "Blocks", rarity: 7 },
  { id: "blast_furnace", name: "Blast Furnace", category: "Blocks", rarity: 7 },
  { id: "smoker", name: "Smoker", category: "Blocks", rarity: 7 },
  { id: "campfire", name: "Campfire", category: "Blocks", rarity: 7 },
  { id: "soul_campfire", name: "Soul Campfire", category: "Blocks", rarity: 7 },
  { id: "hopper", name: "Hopper", category: "Redstone", rarity: 7 },
  { id: "dispenser", name: "Dispenser", category: "Redstone", rarity: 7 },
  { id: "dropper", name: "Dropper", category: "Redstone", rarity: 7 },
  { id: "piston", name: "Piston", category: "Redstone", rarity: 7 },
  { id: "sticky_piston", name: "Sticky Piston", category: "Redstone", rarity: 7 },
  { id: "observer", name: "Observer", category: "Redstone", rarity: 7 },
  { id: "repeater", name: "Redstone Repeater", category: "Redstone", rarity: 7 },
  { id: "comparator", name: "Redstone Comparator", category: "Redstone", rarity: 7 },
  { id: "redstone_lamp", name: "Redstone Lamp", category: "Redstone", rarity: 7 },
  { id: "redstone_torch", name: "Redstone Torch", category: "Redstone", rarity: 7 },
  { id: "daylight_detector", name: "Daylight Detector", category: "Redstone", rarity: 7 },
  { id: "target", name: "Target", category: "Redstone", rarity: 7 },
  { id: "lever", name: "Lever", category: "Redstone", rarity: 7 },
  { id: "tripwire_hook", name: "Tripwire Hook", category: "Redstone", rarity: 7 },
  { id: "lightning_rod", name: "Lightning Rod", category: "Blocks", rarity: 7 },
  { id: "scaffolding", name: "Scaffolding", category: "Blocks", rarity: 7 },
  { id: "loom", name: "Loom", category: "Blocks", rarity: 7 },
  { id: "cartography_table", name: "Cartography Table", category: "Blocks", rarity: 7 },
  { id: "fletching_table", name: "Fletching Table", category: "Blocks", rarity: 7 },
  { id: "smithing_table", name: "Smithing Table", category: "Blocks", rarity: 7 },
  { id: "stonecutter", name: "Stonecutter", category: "Blocks", rarity: 7 },
  { id: "jukebox", name: "Jukebox", category: "Blocks", rarity: 7 },
  { id: "note_block", name: "Note Block", category: "Blocks", rarity: 7 },
  { id: "bell", name: "Bell", category: "Blocks", rarity: 7 },
  { id: "lantern", name: "Lantern", category: "Blocks", rarity: 7 },
  { id: "soul_lantern", name: "Soul Lantern", category: "Blocks", rarity: 7 },
  { id: "item_frame", name: "Item Frame", category: "Blocks", rarity: 7 },
  { id: "glow_item_frame", name: "Glow Item Frame", category: "Blocks", rarity: 7 },
  { id: "painting", name: "Painting", category: "Blocks", rarity: 7 },
  { id: "armor_stand", name: "Armor Stand", category: "Blocks", rarity: 7 },
  { id: "flower_pot", name: "Flower Pot", category: "Blocks", rarity: 7 },
  { id: "crafter", name: "Crafter", category: "Blocks", rarity: 7 },
  { id: "trial_spawner", name: "Trial Spawner", category: "Blocks", rarity: 7 },
  { id: "vault", name: "Vault", category: "Blocks", rarity: 7 },
  { id: "cauldron", name: "Cauldron", category: "Blocks", rarity: 7 },
  { id: "egg", name: "Egg", category: "Materials", rarity: 7 },
  { id: "cooked_beef", name: "Steak", category: "Food", rarity: 7 },
  { id: "cooked_porkchop", name: "Cooked Porkchop", category: "Food", rarity: 7 },
  { id: "cooked_chicken", name: "Cooked Chicken", category: "Food", rarity: 7 },
  { id: "cooked_mutton", name: "Cooked Mutton", category: "Food", rarity: 7 },
  { id: "cooked_rabbit", name: "Cooked Rabbit", category: "Food", rarity: 7 },
  { id: "cooked_cod", name: "Cooked Cod", category: "Food", rarity: 7 },
  { id: "cooked_salmon", name: "Cooked Salmon", category: "Food", rarity: 7 },
  { id: "rabbit_stew", name: "Rabbit Stew", category: "Food", rarity: 7 },
  { id: "mushroom_stew", name: "Mushroom Stew", category: "Food", rarity: 7 },
  { id: "beetroot_soup", name: "Beetroot Soup", category: "Food", rarity: 7 },
  { id: "baked_potato", name: "Baked Potato", category: "Food", rarity: 7 },
  { id: "bread", name: "Bread", category: "Food", rarity: 7 },
  { id: "pumpkin_pie", name: "Pumpkin Pie", category: "Food", rarity: 7 },
  { id: "cookie", name: "Cookie", category: "Food", rarity: 7 },
  { id: "cake", name: "Cake", category: "Food", rarity: 7 },
  { id: "suspicious_stew", name: "Suspicious Stew", category: "Food", rarity: 7 },

  // ── Rarity 8 — Very common / basic resources ──
  { id: "wheat", name: "Wheat", category: "Food", rarity: 8 },
  { id: "apple", name: "Apple", category: "Food", rarity: 8 },
  { id: "carrot", name: "Carrot", category: "Food", rarity: 8 },
  { id: "potato", name: "Potato", category: "Food", rarity: 8 },
  { id: "beetroot", name: "Beetroot", category: "Food", rarity: 8 },
  { id: "beef", name: "Raw Beef", category: "Food", rarity: 8 },
  { id: "porkchop", name: "Raw Porkchop", category: "Food", rarity: 8 },
  { id: "chicken", name: "Raw Chicken", category: "Food", rarity: 8 },
  { id: "mutton", name: "Raw Mutton", category: "Food", rarity: 8 },
  { id: "rabbit", name: "Raw Rabbit", category: "Food", rarity: 8 },
  { id: "cod", name: "Raw Cod", category: "Food", rarity: 8 },
  { id: "salmon", name: "Raw Salmon", category: "Food", rarity: 8 },
  { id: "tropical_fish", name: "Tropical Fish", category: "Food", rarity: 8 },
  { id: "melon_slice", name: "Melon Slice", category: "Food", rarity: 8 },
  { id: "poisonous_potato", name: "Poisonous Potato", category: "Food", rarity: 8 },
  { id: "white_dye", name: "White Dye", category: "Dyes", rarity: 8 },
  { id: "orange_dye", name: "Orange Dye", category: "Dyes", rarity: 8 },
  { id: "magenta_dye", name: "Magenta Dye", category: "Dyes", rarity: 8 },
  { id: "light_blue_dye", name: "Light Blue Dye", category: "Dyes", rarity: 8 },
  { id: "yellow_dye", name: "Yellow Dye", category: "Dyes", rarity: 8 },
  { id: "lime_dye", name: "Lime Dye", category: "Dyes", rarity: 8 },
  { id: "pink_dye", name: "Pink Dye", category: "Dyes", rarity: 8 },
  { id: "gray_dye", name: "Gray Dye", category: "Dyes", rarity: 8 },
  { id: "light_gray_dye", name: "Light Gray Dye", category: "Dyes", rarity: 8 },
  { id: "cyan_dye", name: "Cyan Dye", category: "Dyes", rarity: 8 },
  { id: "purple_dye", name: "Purple Dye", category: "Dyes", rarity: 8 },
  { id: "blue_dye", name: "Blue Dye", category: "Dyes", rarity: 8 },
  { id: "brown_dye", name: "Brown Dye", category: "Dyes", rarity: 8 },
  { id: "green_dye", name: "Green Dye", category: "Dyes", rarity: 8 },
  { id: "red_dye", name: "Red Dye", category: "Dyes", rarity: 8 },
  { id: "black_dye", name: "Black Dye", category: "Dyes", rarity: 8 },
  { id: "white_wool", name: "White Wool", category: "Wool", rarity: 8 },
  { id: "orange_wool", name: "Orange Wool", category: "Wool", rarity: 8 },
  { id: "magenta_wool", name: "Magenta Wool", category: "Wool", rarity: 8 },
  { id: "light_blue_wool", name: "Light Blue Wool", category: "Wool", rarity: 8 },
  { id: "yellow_wool", name: "Yellow Wool", category: "Wool", rarity: 8 },
  { id: "lime_wool", name: "Lime Wool", category: "Wool", rarity: 8 },
  { id: "pink_wool", name: "Pink Wool", category: "Wool", rarity: 8 },
  { id: "gray_wool", name: "Gray Wool", category: "Wool", rarity: 8 },
  { id: "light_gray_wool", name: "Light Gray Wool", category: "Wool", rarity: 8 },
  { id: "cyan_wool", name: "Cyan Wool", category: "Wool", rarity: 8 },
  { id: "purple_wool", name: "Purple Wool", category: "Wool", rarity: 8 },
  { id: "blue_wool", name: "Blue Wool", category: "Wool", rarity: 8 },
  { id: "brown_wool", name: "Brown Wool", category: "Wool", rarity: 8 },
  { id: "green_wool", name: "Green Wool", category: "Wool", rarity: 8 },
  { id: "red_wool", name: "Red Wool", category: "Wool", rarity: 8 },
  { id: "black_wool", name: "Black Wool", category: "Wool", rarity: 8 },
  { id: "oak_log", name: "Oak Log", category: "Wood", rarity: 8 },
  { id: "spruce_log", name: "Spruce Log", category: "Wood", rarity: 8 },
  { id: "birch_log", name: "Birch Log", category: "Wood", rarity: 8 },
  { id: "jungle_log", name: "Jungle Log", category: "Wood", rarity: 8 },
  { id: "acacia_log", name: "Acacia Log", category: "Wood", rarity: 8 },
  { id: "dark_oak_log", name: "Dark Oak Log", category: "Wood", rarity: 8 },
  { id: "mangrove_log", name: "Mangrove Log", category: "Wood", rarity: 8 },
  { id: "cherry_log", name: "Cherry Log", category: "Wood", rarity: 8 },
  { id: "bamboo_block", name: "Bamboo Block", category: "Wood", rarity: 8 },
  { id: "oak_planks", name: "Oak Planks", category: "Wood", rarity: 8 },
  { id: "spruce_planks", name: "Spruce Planks", category: "Wood", rarity: 8 },
  { id: "birch_planks", name: "Birch Planks", category: "Wood", rarity: 8 },
  { id: "jungle_planks", name: "Jungle Planks", category: "Wood", rarity: 8 },
  { id: "acacia_planks", name: "Acacia Planks", category: "Wood", rarity: 8 },
  { id: "dark_oak_planks", name: "Dark Oak Planks", category: "Wood", rarity: 8 },
  { id: "mangrove_planks", name: "Mangrove Planks", category: "Wood", rarity: 8 },
  { id: "cherry_planks", name: "Cherry Planks", category: "Wood", rarity: 8 },
  { id: "bamboo_planks", name: "Bamboo Planks", category: "Wood", rarity: 8 },
  { id: "crimson_planks", name: "Crimson Planks", category: "Wood", rarity: 8 },
  { id: "warped_planks", name: "Warped Planks", category: "Wood", rarity: 8 },
  { id: "stone", name: "Stone", category: "Blocks", rarity: 8 },
  { id: "cobblestone", name: "Cobblestone", category: "Blocks", rarity: 8 },
  { id: "stone_bricks", name: "Stone Bricks", category: "Blocks", rarity: 8 },
  { id: "granite", name: "Granite", category: "Blocks", rarity: 8 },
  { id: "diorite", name: "Diorite", category: "Blocks", rarity: 8 },
  { id: "andesite", name: "Andesite", category: "Blocks", rarity: 8 },
  { id: "deepslate", name: "Deepslate", category: "Blocks", rarity: 8 },
  { id: "cobbled_deepslate", name: "Cobbled Deepslate", category: "Blocks", rarity: 8 },
  { id: "tuff", name: "Tuff", category: "Blocks", rarity: 8 },
  { id: "calcite", name: "Calcite", category: "Blocks", rarity: 8 },
  { id: "sandstone", name: "Sandstone", category: "Blocks", rarity: 8 },
  { id: "red_sandstone", name: "Red Sandstone", category: "Blocks", rarity: 8 },
  { id: "bricks", name: "Bricks", category: "Blocks", rarity: 8 },
  { id: "brick", name: "Brick", category: "Materials", rarity: 8 },
  { id: "mud_bricks", name: "Mud Bricks", category: "Blocks", rarity: 8 },
  { id: "netherrack", name: "Netherrack", category: "Blocks", rarity: 8 },
  { id: "soul_sand", name: "Soul Sand", category: "Blocks", rarity: 8 },
  { id: "basalt", name: "Basalt", category: "Blocks", rarity: 8 },
  { id: "blackstone", name: "Blackstone", category: "Blocks", rarity: 8 },
  { id: "end_stone", name: "End Stone", category: "Blocks", rarity: 8 },
  { id: "purpur_block", name: "Purpur Block", category: "Blocks", rarity: 8 },
  { id: "glass", name: "Glass", category: "Blocks", rarity: 8 },
  { id: "glass_pane", name: "Glass Pane", category: "Blocks", rarity: 8 },
  { id: "torch", name: "Torch", category: "Blocks", rarity: 8 },
  { id: "soul_torch", name: "Soul Torch", category: "Blocks", rarity: 8 },
  { id: "cactus", name: "Cactus", category: "Plants", rarity: 8 },
  { id: "sugar_cane", name: "Sugar Cane", category: "Plants", rarity: 8 },
  { id: "bamboo", name: "Bamboo", category: "Plants", rarity: 8 },
  { id: "pumpkin", name: "Pumpkin", category: "Plants", rarity: 8 },
  { id: "melon", name: "Melon", category: "Plants", rarity: 8 },
  { id: "brown_mushroom", name: "Brown Mushroom", category: "Plants", rarity: 8 },
  { id: "red_mushroom", name: "Red Mushroom", category: "Plants", rarity: 8 },
  { id: "dandelion", name: "Dandelion", category: "Plants", rarity: 8 },
  { id: "poppy", name: "Poppy", category: "Plants", rarity: 8 },
  { id: "blue_orchid", name: "Blue Orchid", category: "Plants", rarity: 8 },
  { id: "allium", name: "Allium", category: "Plants", rarity: 8 },
  { id: "wither_rose", name: "Wither Rose", category: "Plants", rarity: 8 },
  { id: "torchflower", name: "Torchflower", category: "Plants", rarity: 8 },
  { id: "cherry_sapling", name: "Cherry Sapling", category: "Plants", rarity: 8 },
  { id: "nether_wart_block", name: "Nether Wart Block", category: "Blocks", rarity: 8 },
  { id: "crimson_stem", name: "Crimson Stem", category: "Blocks", rarity: 8 },
  { id: "warped_stem", name: "Warped Stem", category: "Blocks", rarity: 8 },
  { id: "prismarine", name: "Prismarine", category: "Blocks", rarity: 8 },
  { id: "dark_prismarine", name: "Dark Prismarine", category: "Blocks", rarity: 8 },
  { id: "terracotta", name: "Terracotta", category: "Blocks", rarity: 8 },
  { id: "white_terracotta", name: "White Terracotta", category: "Blocks", rarity: 8 },
  { id: "white_concrete", name: "White Concrete", category: "Blocks", rarity: 8 },
  { id: "white_stained_glass", name: "White Stained Glass", category: "Blocks", rarity: 8 },
];

// When no query: return all items sorted rarity asc (rarest first), capped at 20
// When query: fuzzy match, sort by match quality then rarity
export function searchMcItems(query: string): McItem[] {
  const q = query.toLowerCase().trim();
  if (!q) {
    return [...MC_ITEMS].sort((a, b) => a.rarity - b.rarity).slice(0, 20);
  }
  return MC_ITEMS
    .filter(
      (item) =>
        item.name.toLowerCase().includes(q) ||
        item.id.toLowerCase().includes(q) ||
        item.category.toLowerCase().includes(q),
    )
    .sort((a, b) => {
      // Exact name start > contains > rarity
      const aStart = a.name.toLowerCase().startsWith(q) ? 0 : 1;
      const bStart = b.name.toLowerCase().startsWith(q) ? 0 : 1;
      if (aStart !== bStart) return aStart - bStart;
      return a.rarity - b.rarity;
    })
    .slice(0, 20);
}
