export type McItem = {
  id: string;        // internal key
  name: string;      // display name
  icon: string;      // exact Minecraft Wiki Invicon filename (without base URL)
  category: string;
  rarity: number;    // 1 = rarest, 8 = most common
};

const BASE = "https://minecraft.wiki/images/";

// Every survival-obtainable item in MC 1.21.1
// Icons verified against https://minecraft.wiki/images/Invicon_<slug>
export const MC_ITEMS: McItem[] = [
  // ── Rarity 1 — Legendary ──
  { id: "dragon_egg",            name: "Dragon Egg",               icon: "Invicon_Dragon_Egg.png",               category: "Blocks",    rarity: 1 },
  { id: "elytra",                name: "Elytra",                   icon: "Invicon_Elytra.png",                   category: "Armor",     rarity: 1 },
  { id: "nether_star",           name: "Nether Star",              icon: "Invicon_Nether_Star.gif",              category: "Materials", rarity: 1 },
  { id: "beacon",                name: "Beacon",                   icon: "Invicon_Beacon.png",                   category: "Blocks",    rarity: 1 },
  { id: "enchanted_golden_apple",name: "Enchanted Golden Apple",   icon: "Invicon_Enchanted_Golden_Apple.gif",   category: "Food",      rarity: 1 },
  { id: "end_crystal",           name: "End Crystal",              icon: "Invicon_End_Crystal.gif",              category: "Combat",    rarity: 1 },

  // ── Rarity 2 — Very Rare ──
  { id: "netherite_ingot",       name: "Netherite Ingot",          icon: "Invicon_Netherite_Ingot.png",          category: "Materials", rarity: 2 },
  { id: "netherite_scrap",       name: "Netherite Scrap",          icon: "Invicon_Netherite_Scrap.png",          category: "Materials", rarity: 2 },
  { id: "ancient_debris",        name: "Ancient Debris",           icon: "Invicon_Ancient_Debris.png",           category: "Materials", rarity: 2 },
  { id: "netherite_block",       name: "Block of Netherite",       icon: "Invicon_Block_of_Netherite.png",       category: "Blocks",    rarity: 2 },
  { id: "netherite_upgrade",     name: "Netherite Upgrade Template",icon: "Invicon_Netherite_Upgrade.png",       category: "Smithing",  rarity: 2 },
  { id: "netherite_sword",       name: "Netherite Sword",          icon: "Invicon_Netherite_Sword.png",          category: "Weapons",   rarity: 2 },
  { id: "netherite_pickaxe",     name: "Netherite Pickaxe",        icon: "Invicon_Netherite_Pickaxe.png",        category: "Tools",     rarity: 2 },
  { id: "netherite_axe",         name: "Netherite Axe",            icon: "Invicon_Netherite_Axe.png",            category: "Tools",     rarity: 2 },
  { id: "netherite_shovel",      name: "Netherite Shovel",         icon: "Invicon_Netherite_Shovel.png",         category: "Tools",     rarity: 2 },
  { id: "netherite_hoe",         name: "Netherite Hoe",            icon: "Invicon_Netherite_Hoe.png",            category: "Tools",     rarity: 2 },
  { id: "netherite_helmet",      name: "Netherite Helmet",         icon: "Invicon_Netherite_Helmet.png",         category: "Armor",     rarity: 2 },
  { id: "netherite_chestplate",  name: "Netherite Chestplate",     icon: "Invicon_Netherite_Chestplate.png",     category: "Armor",     rarity: 2 },
  { id: "netherite_leggings",    name: "Netherite Leggings",       icon: "Invicon_Netherite_Leggings.png",       category: "Armor",     rarity: 2 },
  { id: "netherite_boots",       name: "Netherite Boots",          icon: "Invicon_Netherite_Boots.png",          category: "Armor",     rarity: 2 },
  { id: "totem_of_undying",      name: "Totem of Undying",         icon: "Invicon_Totem_of_Undying.png",         category: "Combat",    rarity: 2 },
  { id: "trident",               name: "Trident",                  icon: "Invicon_Trident.png",                  category: "Weapons",   rarity: 2 },
  { id: "mace",                  name: "Mace",                     icon: "Invicon_Mace.png",                     category: "Weapons",   rarity: 2 },
  { id: "heavy_core",            name: "Heavy Core",               icon: "Invicon_Heavy_Core.png",               category: "Materials", rarity: 2 },
  { id: "heart_of_the_sea",      name: "Heart of the Sea",         icon: "Invicon_Heart_of_the_Sea.png",         category: "Ocean",     rarity: 2 },
  { id: "conduit",               name: "Conduit",                  icon: "Invicon_Conduit.png",                  category: "Blocks",    rarity: 2 },
  { id: "silence_trim",          name: "Silence Armor Trim",       icon: "Invicon_Silence_Armor_Trim_Smithing_Template.png", category: "Smithing", rarity: 2 },
  { id: "wither_skeleton_skull", name: "Wither Skeleton Skull",    icon: "Invicon_Wither_Skeleton_Skull.png",    category: "Combat",    rarity: 2 },
  { id: "reinforced_deepslate",  name: "Reinforced Deepslate",     icon: "Invicon_Reinforced_Deepslate.png",     category: "Blocks",    rarity: 2 },
  { id: "disc_pigstep",          name: "Music Disc (Pigstep)",     icon: "Invicon_Music_Disc_Pigstep.png",       category: "Music",     rarity: 2 },
  { id: "disc_otherside",        name: "Music Disc (Otherside)",   icon: "Invicon_Music_Disc_Otherside.png",     category: "Music",     rarity: 2 },
  { id: "disc_relic",            name: "Music Disc (Relic)",       icon: "Invicon_Music_Disc_Relic.png",         category: "Music",     rarity: 2 },
  { id: "disc_precipice",        name: "Music Disc (Precipice)",   icon: "Invicon_Music_Disc_Precipice.png",     category: "Music",     rarity: 2 },
  { id: "disc_creator",          name: "Music Disc (Creator)",     icon: "Invicon_Music_Disc_Creator.png",       category: "Music",     rarity: 2 },

  // ── Rarity 3 — Rare ──
  { id: "shulker_shell",         name: "Shulker Shell",            icon: "Invicon_Shulker_Shell.png",            category: "Materials", rarity: 3 },
  { id: "shulker_box",           name: "Shulker Box",              icon: "Invicon_Shulker_Box.png",              category: "Blocks",    rarity: 3 },
  { id: "white_shulker_box",     name: "White Shulker Box",        icon: "Invicon_White_Shulker_Box.png",        category: "Blocks",    rarity: 3 },
  { id: "orange_shulker_box",    name: "Orange Shulker Box",       icon: "Invicon_Orange_Shulker_Box.png",       category: "Blocks",    rarity: 3 },
  { id: "magenta_shulker_box",   name: "Magenta Shulker Box",      icon: "Invicon_Magenta_Shulker_Box.png",      category: "Blocks",    rarity: 3 },
  { id: "light_blue_shulker_box",name: "Light Blue Shulker Box",   icon: "Invicon_Light_Blue_Shulker_Box.png",   category: "Blocks",    rarity: 3 },
  { id: "yellow_shulker_box",    name: "Yellow Shulker Box",       icon: "Invicon_Yellow_Shulker_Box.png",       category: "Blocks",    rarity: 3 },
  { id: "lime_shulker_box",      name: "Lime Shulker Box",         icon: "Invicon_Lime_Shulker_Box.png",         category: "Blocks",    rarity: 3 },
  { id: "pink_shulker_box",      name: "Pink Shulker Box",         icon: "Invicon_Pink_Shulker_Box.png",         category: "Blocks",    rarity: 3 },
  { id: "gray_shulker_box",      name: "Gray Shulker Box",         icon: "Invicon_Gray_Shulker_Box.png",         category: "Blocks",    rarity: 3 },
  { id: "light_gray_shulker_box",name: "Light Gray Shulker Box",   icon: "Invicon_Light_Gray_Shulker_Box.png",   category: "Blocks",    rarity: 3 },
  { id: "cyan_shulker_box",      name: "Cyan Shulker Box",         icon: "Invicon_Cyan_Shulker_Box.png",         category: "Blocks",    rarity: 3 },
  { id: "purple_shulker_box",    name: "Purple Shulker Box",       icon: "Invicon_Purple_Shulker_Box.png",       category: "Blocks",    rarity: 3 },
  { id: "blue_shulker_box",      name: "Blue Shulker Box",         icon: "Invicon_Blue_Shulker_Box.png",         category: "Blocks",    rarity: 3 },
  { id: "brown_shulker_box",     name: "Brown Shulker Box",        icon: "Invicon_Brown_Shulker_Box.png",        category: "Blocks",    rarity: 3 },
  { id: "green_shulker_box",     name: "Green Shulker Box",        icon: "Invicon_Green_Shulker_Box.png",        category: "Blocks",    rarity: 3 },
  { id: "red_shulker_box",       name: "Red Shulker Box",          icon: "Invicon_Red_Shulker_Box.png",          category: "Blocks",    rarity: 3 },
  { id: "black_shulker_box",     name: "Black Shulker Box",        icon: "Invicon_Black_Shulker_Box.png",        category: "Blocks",    rarity: 3 },
  { id: "dragon_breath",         name: "Dragon's Breath",          icon: "Invicon_Dragon's_Breath.png",          category: "Materials", rarity: 3 },
  { id: "dragon_head",           name: "Dragon Head",              icon: "Invicon_Dragon_Head.png",              category: "Blocks",    rarity: 3 },
  { id: "ghast_tear",            name: "Ghast Tear",               icon: "Invicon_Ghast_Tear.png",               category: "Materials", rarity: 3 },
  { id: "ominous_trial_key",     name: "Ominous Trial Key",        icon: "Invicon_Ominous_Trial_Key.png",        category: "Combat",    rarity: 3 },
  { id: "ominous_bottle",        name: "Ominous Bottle",           icon: "Invicon_Ominous_Bottle.png",           category: "Combat",    rarity: 3 },
  { id: "enchanted_book",        name: "Enchanted Book",           icon: "Invicon_Enchanted_Book.gif",           category: "Enchanting",rarity: 3 },
  { id: "exp_bottle",            name: "Bottle o' Enchanting",     icon: "Invicon_Bottle_o'_Enchanting.png",     category: "Enchanting",rarity: 3 },
  { id: "eye_of_ender",          name: "Eye of Ender",             icon: "Invicon_Eye_of_Ender.png",             category: "Materials", rarity: 3 },
  { id: "golden_apple",          name: "Golden Apple",             icon: "Invicon_Golden_Apple.png",             category: "Food",      rarity: 3 },
  { id: "recovery_compass",      name: "Recovery Compass",         icon: "Invicon_Recovery_Compass.gif",         category: "Tools",     rarity: 3 },
  { id: "coast_trim",            name: "Coast Armor Trim",         icon: "Invicon_Coast_Armor_Trim_Smithing_Template.png",   category: "Smithing", rarity: 3 },
  { id: "dune_trim",             name: "Dune Armor Trim",          icon: "Invicon_Dune_Armor_Trim_Smithing_Template.png",    category: "Smithing", rarity: 3 },
  { id: "eye_trim",              name: "Eye Armor Trim",           icon: "Invicon_Eye_Armor_Trim_Smithing_Template.png",     category: "Smithing", rarity: 3 },
  { id: "host_trim",             name: "Host Armor Trim",          icon: "Invicon_Host_Armor_Trim_Smithing_Template.png",    category: "Smithing", rarity: 3 },
  { id: "raiser_trim",           name: "Raiser Armor Trim",        icon: "Invicon_Raiser_Armor_Trim_Smithing_Template.png",  category: "Smithing", rarity: 3 },
  { id: "rib_trim",              name: "Rib Armor Trim",           icon: "Invicon_Rib_Armor_Trim_Smithing_Template.png",     category: "Smithing", rarity: 3 },
  { id: "sentry_trim",           name: "Sentry Armor Trim",        icon: "Invicon_Sentry_Armor_Trim_Smithing_Template.png",  category: "Smithing", rarity: 3 },
  { id: "shaper_trim",           name: "Shaper Armor Trim",        icon: "Invicon_Shaper_Armor_Trim_Smithing_Template.png",  category: "Smithing", rarity: 3 },
  { id: "snout_trim",            name: "Snout Armor Trim",         icon: "Invicon_Snout_Armor_Trim_Smithing_Template.png",   category: "Smithing", rarity: 3 },
  { id: "spire_trim",            name: "Spire Armor Trim",         icon: "Invicon_Spire_Armor_Trim_Smithing_Template.png",   category: "Smithing", rarity: 3 },
  { id: "tide_trim",             name: "Tide Armor Trim",          icon: "Invicon_Tide_Armor_Trim_Smithing_Template.png",    category: "Smithing", rarity: 3 },
  { id: "vex_trim",              name: "Vex Armor Trim",           icon: "Invicon_Vex_Armor_Trim_Smithing_Template.png",     category: "Smithing", rarity: 3 },
  { id: "ward_trim",             name: "Ward Armor Trim",          icon: "Invicon_Ward_Armor_Trim_Smithing_Template.png",    category: "Smithing", rarity: 3 },
  { id: "wayfinder_trim",        name: "Wayfinder Armor Trim",     icon: "Invicon_Wayfinder_Armor_Trim_Smithing_Template.png",category: "Smithing",rarity: 3 },
  { id: "wild_trim",             name: "Wild Armor Trim",          icon: "Invicon_Wild_Armor_Trim_Smithing_Template.png",    category: "Smithing", rarity: 3 },
  { id: "bolt_trim",             name: "Bolt Armor Trim",          icon: "Invicon_Bolt_Armor_Trim_Smithing_Template.png",    category: "Smithing", rarity: 3 },
  { id: "flow_trim",             name: "Flow Armor Trim",          icon: "Invicon_Flow_Armor_Trim_Smithing_Template.png",    category: "Smithing", rarity: 3 },
  { id: "disc_13",               name: "Music Disc (13)",          icon: "Invicon_Music_Disc_13.png",            category: "Music",     rarity: 3 },
  { id: "disc_cat",              name: "Music Disc (Cat)",         icon: "Invicon_Music_Disc_Cat.png",           category: "Music",     rarity: 3 },
  { id: "disc_blocks",           name: "Music Disc (Blocks)",      icon: "Invicon_Music_Disc_Blocks.png",        category: "Music",     rarity: 3 },
  { id: "disc_chirp",            name: "Music Disc (Chirp)",       icon: "Invicon_Music_Disc_Chirp.png",         category: "Music",     rarity: 3 },
  { id: "disc_far",              name: "Music Disc (Far)",         icon: "Invicon_Music_Disc_Far.png",           category: "Music",     rarity: 3 },
  { id: "disc_mall",             name: "Music Disc (Mall)",        icon: "Invicon_Music_Disc_Mall.png",          category: "Music",     rarity: 3 },
  { id: "disc_mellohi",          name: "Music Disc (Mellohi)",     icon: "Invicon_Music_Disc_Mellohi.png",       category: "Music",     rarity: 3 },
  { id: "disc_stal",             name: "Music Disc (Stal)",        icon: "Invicon_Music_Disc_Stal.png",          category: "Music",     rarity: 3 },
  { id: "disc_strad",            name: "Music Disc (Strad)",       icon: "Invicon_Music_Disc_Strad.png",         category: "Music",     rarity: 3 },
  { id: "disc_ward",             name: "Music Disc (Ward)",        icon: "Invicon_Music_Disc_Ward.png",          category: "Music",     rarity: 3 },
  { id: "disc_11",               name: "Music Disc (11)",          icon: "Invicon_Music_Disc_11.png",            category: "Music",     rarity: 3 },
  { id: "disc_wait",             name: "Music Disc (Wait)",        icon: "Invicon_Music_Disc_Wait.png",          category: "Music",     rarity: 3 },
  { id: "disc_5",                name: "Music Disc (5)",           icon: "Invicon_Music_Disc_5.png",             category: "Music",     rarity: 3 },
  { id: "disc_creator_music_box",name: "Music Disc (Creator Music Box)",icon: "Invicon_Music_Disc_Creator_Music_Box.png",category: "Music",rarity: 3 },
  { id: "disc_fragment_5",       name: "Disc Fragment (5)",        icon: "Invicon_Disc_Fragment_5.png",          category: "Music",     rarity: 3 },

  // ── Rarity 4 — Uncommon ──
  { id: "diamond",               name: "Diamond",                  icon: "Invicon_Diamond.png",                  category: "Materials", rarity: 4 },
  { id: "diamond_block",         name: "Block of Diamond",         icon: "Invicon_Block_of_Diamond.png",         category: "Blocks",    rarity: 4 },
  { id: "diamond_sword",         name: "Diamond Sword",            icon: "Invicon_Diamond_Sword.png",            category: "Weapons",   rarity: 4 },
  { id: "diamond_pickaxe",       name: "Diamond Pickaxe",          icon: "Invicon_Diamond_Pickaxe.png",          category: "Tools",     rarity: 4 },
  { id: "diamond_axe",           name: "Diamond Axe",              icon: "Invicon_Diamond_Axe.png",              category: "Tools",     rarity: 4 },
  { id: "diamond_shovel",        name: "Diamond Shovel",           icon: "Invicon_Diamond_Shovel.png",           category: "Tools",     rarity: 4 },
  { id: "diamond_hoe",           name: "Diamond Hoe",              icon: "Invicon_Diamond_Hoe.png",              category: "Tools",     rarity: 4 },
  { id: "diamond_helmet",        name: "Diamond Helmet",           icon: "Invicon_Diamond_Helmet.png",           category: "Armor",     rarity: 4 },
  { id: "diamond_chestplate",    name: "Diamond Chestplate",       icon: "Invicon_Diamond_Chestplate.png",       category: "Armor",     rarity: 4 },
  { id: "diamond_leggings",      name: "Diamond Leggings",         icon: "Invicon_Diamond_Leggings.png",         category: "Armor",     rarity: 4 },
  { id: "diamond_boots",         name: "Diamond Boots",            icon: "Invicon_Diamond_Boots.png",            category: "Armor",     rarity: 4 },
  { id: "diamond_horse_armor",   name: "Diamond Horse Armor",      icon: "Invicon_Diamond_Horse_Armor.png",      category: "Armor",     rarity: 4 },
  { id: "emerald",               name: "Emerald",                  icon: "Invicon_Emerald.png",                  category: "Materials", rarity: 4 },
  { id: "emerald_block",         name: "Block of Emerald",         icon: "Invicon_Block_of_Emerald.png",         category: "Blocks",    rarity: 4 },
  { id: "ender_pearl",           name: "Ender Pearl",              icon: "Invicon_Ender_Pearl.png",              category: "Materials", rarity: 4 },
  { id: "blaze_rod",             name: "Blaze Rod",                icon: "Invicon_Blaze_Rod.png",                category: "Materials", rarity: 4 },
  { id: "blaze_powder",          name: "Blaze Powder",             icon: "Invicon_Blaze_Powder.png",             category: "Materials", rarity: 4 },
  { id: "magma_cream",           name: "Magma Cream",              icon: "Invicon_Magma_Cream.png",              category: "Materials", rarity: 4 },
  { id: "prismarine_crystals",   name: "Prismarine Crystals",      icon: "Invicon_Prismarine_Crystals.png",      category: "Ocean",     rarity: 4 },
  { id: "prismarine_shard",      name: "Prismarine Shard",         icon: "Invicon_Prismarine_Shard.png",         category: "Ocean",     rarity: 4 },
  { id: "nautilus_shell",        name: "Nautilus Shell",           icon: "Invicon_Nautilus_Shell.png",           category: "Ocean",     rarity: 4 },
  { id: "phantom_membrane",      name: "Phantom Membrane",         icon: "Invicon_Phantom_Membrane.png",         category: "Materials", rarity: 4 },
  { id: "breeze_rod",            name: "Breeze Rod",               icon: "Invicon_Breeze_Rod.png",               category: "Materials", rarity: 4 },
  { id: "wind_charge",           name: "Wind Charge",              icon: "Invicon_Wind_Charge.png",              category: "Combat",    rarity: 4 },
  { id: "name_tag",              name: "Name Tag",                 icon: "Invicon_Name_Tag.png",                 category: "Tools",     rarity: 4 },
  { id: "saddle",                name: "Saddle",                   icon: "Invicon_Saddle.png",                   category: "Tools",     rarity: 4 },
  { id: "rabbit_foot",           name: "Rabbit's Foot",            icon: "Invicon_Rabbit's_Foot.png",            category: "Potions",   rarity: 4 },
  { id: "amethyst_shard",        name: "Amethyst Shard",           icon: "Invicon_Amethyst_Shard.png",           category: "Materials", rarity: 4 },
  { id: "amethyst_block",        name: "Block of Amethyst",        icon: "Invicon_Block_of_Amethyst.png",        category: "Blocks",    rarity: 4 },
  { id: "budding_amethyst",      name: "Budding Amethyst",         icon: "Invicon_Budding_Amethyst.png",         category: "Blocks",    rarity: 4 },
  { id: "spyglass",              name: "Spyglass",                 icon: "Invicon_Spyglass.png",                 category: "Tools",     rarity: 4 },
  { id: "turtle_shell",          name: "Turtle Shell",             icon: "Invicon_Turtle_Shell.png",             category: "Armor",     rarity: 4 },
  { id: "scute",                 name: "Scute",                    icon: "Invicon_Turtle_Scute.png",             category: "Materials", rarity: 4 },
  { id: "armadillo_scute",       name: "Armadillo Scute",          icon: "Invicon_Armadillo_Scute.png",          category: "Materials", rarity: 4 },
  { id: "wolf_armor",            name: "Wolf Armor",               icon: "Invicon_Wolf_Armor.png",               category: "Armor",     rarity: 4 },
  { id: "glow_ink_sac",          name: "Glow Ink Sac",             icon: "Invicon_Glow_Ink_Sac.png",             category: "Materials", rarity: 4 },
  { id: "lead",                  name: "Lead",                     icon: "Invicon_Lead.png",                     category: "Tools",     rarity: 4 },
  { id: "crossbow",              name: "Crossbow",                 icon: "Invicon_Crossbow.png",                 category: "Weapons",   rarity: 4 },
  { id: "golden_carrot",         name: "Golden Carrot",            icon: "Invicon_Golden_Carrot.png",            category: "Food",      rarity: 4 },
  { id: "fermented_spider_eye",  name: "Fermented Spider Eye",     icon: "Invicon_Fermented_Spider_Eye.png",     category: "Potions",   rarity: 4 },
  { id: "popped_chorus_fruit",   name: "Popped Chorus Fruit",      icon: "Invicon_Popped_Chorus_Fruit.png",      category: "Materials", rarity: 4 },
  { id: "chorus_fruit",          name: "Chorus Fruit",             icon: "Invicon_Chorus_Fruit.png",             category: "Food",      rarity: 4 },
  { id: "sponge",                name: "Sponge",                   icon: "Invicon_Sponge.png",                   category: "Blocks",    rarity: 4 },

  // ── Rarity 5 — Moderate ──
  { id: "gold_ingot",            name: "Gold Ingot",               icon: "Invicon_Gold_Ingot.png",               category: "Materials", rarity: 5 },
  { id: "gold_nugget",           name: "Gold Nugget",              icon: "Invicon_Gold_Nugget.png",              category: "Materials", rarity: 5 },
  { id: "gold_block",            name: "Block of Gold",            icon: "Invicon_Block_of_Gold.png",            category: "Blocks",    rarity: 5 },
  { id: "raw_gold",              name: "Raw Gold",                 icon: "Invicon_Raw_Gold.png",                 category: "Materials", rarity: 5 },
  { id: "raw_gold_block",        name: "Raw Gold Block",           icon: "Invicon_Raw_Gold_Block.png",           category: "Blocks",    rarity: 5 },
  { id: "golden_sword",          name: "Golden Sword",             icon: "Invicon_Golden_Sword.png",             category: "Weapons",   rarity: 5 },
  { id: "golden_pickaxe",        name: "Golden Pickaxe",           icon: "Invicon_Golden_Pickaxe.png",           category: "Tools",     rarity: 5 },
  { id: "golden_axe",            name: "Golden Axe",               icon: "Invicon_Golden_Axe.png",               category: "Tools",     rarity: 5 },
  { id: "golden_shovel",         name: "Golden Shovel",            icon: "Invicon_Golden_Shovel.png",            category: "Tools",     rarity: 5 },
  { id: "golden_hoe",            name: "Golden Hoe",               icon: "Invicon_Golden_Hoe.png",               category: "Tools",     rarity: 5 },
  { id: "golden_helmet",         name: "Golden Helmet",            icon: "Invicon_Golden_Helmet.png",            category: "Armor",     rarity: 5 },
  { id: "golden_chestplate",     name: "Golden Chestplate",        icon: "Invicon_Golden_Chestplate.png",        category: "Armor",     rarity: 5 },
  { id: "golden_leggings",       name: "Golden Leggings",          icon: "Invicon_Golden_Leggings.png",          category: "Armor",     rarity: 5 },
  { id: "golden_boots",          name: "Golden Boots",             icon: "Invicon_Golden_Boots.png",             category: "Armor",     rarity: 5 },
  { id: "golden_horse_armor",    name: "Golden Horse Armor",       icon: "Invicon_Golden_Horse_Armor.png",       category: "Armor",     rarity: 5 },
  { id: "lapis_lazuli",          name: "Lapis Lazuli",             icon: "Invicon_Lapis_Lazuli.png",             category: "Materials", rarity: 5 },
  { id: "lapis_block",           name: "Lapis Lazuli Block",       icon: "Invicon_Lapis_Lazuli_Block.png",       category: "Blocks",    rarity: 5 },
  { id: "quartz",                name: "Nether Quartz",            icon: "Invicon_Nether_Quartz.png",            category: "Materials", rarity: 5 },
  { id: "quartz_block",          name: "Block of Quartz",          icon: "Invicon_Block_of_Quartz.png",          category: "Blocks",    rarity: 5 },
  { id: "redstone",              name: "Redstone Dust",            icon: "Invicon_Redstone_Dust.png",            category: "Materials", rarity: 5 },
  { id: "redstone_block",        name: "Block of Redstone",        icon: "Invicon_Block_of_Redstone.png",        category: "Blocks",    rarity: 5 },
  { id: "gilded_blackstone",     name: "Gilded Blackstone",        icon: "Invicon_Gilded_Blackstone.png",        category: "Blocks",    rarity: 5 },
  { id: "nether_wart",           name: "Nether Wart",              icon: "Invicon_Nether_Wart.png",              category: "Materials", rarity: 5 },
  { id: "glowstone_dust",        name: "Glowstone Dust",           icon: "Invicon_Glowstone_Dust.png",           category: "Materials", rarity: 5 },
  { id: "glowstone",             name: "Glowstone",                icon: "Invicon_Glowstone.png",                category: "Blocks",    rarity: 5 },
  { id: "sea_lantern",           name: "Sea Lantern",              icon: "Invicon_Sea_Lantern.png",              category: "Blocks",    rarity: 5 },
  { id: "bow",                   name: "Bow",                      icon: "Invicon_Bow.png",                      category: "Weapons",   rarity: 5 },
  { id: "shield",                name: "Shield",                   icon: "Invicon_Shield.png",                   category: "Combat",    rarity: 5 },
  { id: "brush",                 name: "Brush",                    icon: "Invicon_Brush.png",                    category: "Tools",     rarity: 5 },
  { id: "decorated_pot",         name: "Decorated Pot",            icon: "Invicon_Decorated_Pot.png",            category: "Blocks",    rarity: 5 },
  { id: "honeycomb",             name: "Honeycomb",                icon: "Invicon_Honeycomb.png",                category: "Materials", rarity: 5 },
  { id: "honey_bottle",          name: "Honey Bottle",             icon: "Invicon_Honey_Bottle.png",             category: "Food",      rarity: 5 },
  { id: "pufferfish",            name: "Pufferfish",               icon: "Invicon_Pufferfish.png",               category: "Potions",   rarity: 5 },
  { id: "slimeball",             name: "Slimeball",                icon: "Invicon_Slimeball.png",                category: "Materials", rarity: 5 },
  { id: "slime_block",           name: "Slime Block",              icon: "Invicon_Slime_Block.png",              category: "Blocks",    rarity: 5 },
  { id: "magma_block",           name: "Magma Block",              icon: "Invicon_Magma_Block.png",              category: "Blocks",    rarity: 5 },
  { id: "obsidian",              name: "Obsidian",                 icon: "Invicon_Obsidian.png",                 category: "Blocks",    rarity: 5 },
  { id: "crying_obsidian",       name: "Crying Obsidian",          icon: "Invicon_Crying_Obsidian.png",          category: "Blocks",    rarity: 5 },
  { id: "ink_sac",               name: "Ink Sac",                  icon: "Invicon_Ink_Sac.png",                  category: "Materials", rarity: 5 },
  { id: "white_dye",             name: "White Dye",                icon: "Invicon_White_Dye.png",                category: "Dyes",      rarity: 6 },
  { id: "light_gray_dye",        name: "Light Gray Dye",           icon: "Invicon_Light_Gray_Dye.png",           category: "Dyes",      rarity: 6 },
  { id: "gray_dye",              name: "Gray Dye",                 icon: "Invicon_Gray_Dye.png",                 category: "Dyes",      rarity: 6 },
  { id: "black_dye",             name: "Black Dye",                icon: "Invicon_Black_Dye.png",                category: "Dyes",      rarity: 6 },
  { id: "brown_dye",             name: "Brown Dye",                icon: "Invicon_Brown_Dye.png",                category: "Dyes",      rarity: 6 },
  { id: "red_dye",               name: "Red Dye",                  icon: "Invicon_Red_Dye.png",                  category: "Dyes",      rarity: 6 },
  { id: "orange_dye",            name: "Orange Dye",               icon: "Invicon_Orange_Dye.png",               category: "Dyes",      rarity: 6 },
  { id: "yellow_dye",            name: "Yellow Dye",               icon: "Invicon_Yellow_Dye.png",               category: "Dyes",      rarity: 6 },
  { id: "lime_dye",              name: "Lime Dye",                 icon: "Invicon_Lime_Dye.png",                 category: "Dyes",      rarity: 6 },
  { id: "green_dye",             name: "Green Dye",                icon: "Invicon_Green_Dye.png",                category: "Dyes",      rarity: 6 },
  { id: "cyan_dye",              name: "Cyan Dye",                 icon: "Invicon_Cyan_Dye.png",                 category: "Dyes",      rarity: 6 },
  { id: "light_blue_dye",        name: "Light Blue Dye",           icon: "Invicon_Light_Blue_Dye.png",           category: "Dyes",      rarity: 6 },
  { id: "blue_dye",              name: "Blue Dye",                 icon: "Invicon_Blue_Dye.png",                 category: "Dyes",      rarity: 6 },
  { id: "purple_dye",            name: "Purple Dye",               icon: "Invicon_Purple_Dye.png",               category: "Dyes",      rarity: 6 },
  { id: "magenta_dye",           name: "Magenta Dye",              icon: "Invicon_Magenta_Dye.png",              category: "Dyes",      rarity: 6 },
  { id: "pink_dye",              name: "Pink Dye",                 icon: "Invicon_Pink_Dye.png",                 category: "Dyes",      rarity: 6 },
  { id: "gunpowder",             name: "Gunpowder",                icon: "Invicon_Gunpowder.png",                category: "Materials", rarity: 5 },
  { id: "spider_eye",            name: "Spider Eye",               icon: "Invicon_Spider_Eye.png",               category: "Materials", rarity: 5 },
  { id: "string",                name: "String",                   icon: "Invicon_String.png",                   category: "Materials", rarity: 5 },
  { id: "glistering_melon",      name: "Glistering Melon Slice",   icon: "Invicon_Glistering_Melon_Slice.png",   category: "Potions",   rarity: 5 },
  { id: "fire_charge",           name: "Fire Charge",              icon: "Invicon_Fire_Charge.png",              category: "Combat",    rarity: 5 },
  { id: "tnt",                   name: "TNT",                      icon: "Invicon_TNT.png",                      category: "Blocks",    rarity: 5 },
  { id: "spectral_arrow",        name: "Spectral Arrow",           icon: "Invicon_Spectral_Arrow.png",           category: "Combat",    rarity: 5 },
  { id: "firework_rocket",       name: "Firework Rocket",          icon: "Invicon_Firework_Rocket.png",          category: "Misc",      rarity: 5 },
  { id: "firework_star",         name: "Firework Star",            icon: "Invicon_Firework_Star.png",            category: "Misc",      rarity: 5 },
  { id: "water_bottle",          name: "Water Bottle",             icon: "Invicon_Water_Bottle.png",             category: "Potions",   rarity: 5 },

  // ── Rarity 6 — Farmable / Craftable ──
  { id: "iron_ingot",            name: "Iron Ingot",               icon: "Invicon_Iron_Ingot.png",               category: "Materials", rarity: 6 },
  { id: "iron_nugget",           name: "Iron Nugget",              icon: "Invicon_Iron_Nugget.png",              category: "Materials", rarity: 6 },
  { id: "iron_block",            name: "Block of Iron",            icon: "Invicon_Block_of_Iron.png",            category: "Blocks",    rarity: 6 },
  { id: "raw_iron",              name: "Raw Iron",                 icon: "Invicon_Raw_Iron.png",                 category: "Materials", rarity: 6 },
  { id: "raw_iron_block",        name: "Raw Iron Block",           icon: "Invicon_Raw_Iron_Block.png",           category: "Blocks",    rarity: 6 },
  { id: "iron_sword",            name: "Iron Sword",               icon: "Invicon_Iron_Sword.png",               category: "Weapons",   rarity: 6 },
  { id: "iron_pickaxe",          name: "Iron Pickaxe",             icon: "Invicon_Iron_Pickaxe.png",             category: "Tools",     rarity: 6 },
  { id: "iron_axe",              name: "Iron Axe",                 icon: "Invicon_Iron_Axe.png",                 category: "Tools",     rarity: 6 },
  { id: "iron_shovel",           name: "Iron Shovel",              icon: "Invicon_Iron_Shovel.png",              category: "Tools",     rarity: 6 },
  { id: "iron_hoe",              name: "Iron Hoe",                 icon: "Invicon_Iron_Hoe.png",                 category: "Tools",     rarity: 6 },
  { id: "iron_helmet",           name: "Iron Helmet",              icon: "Invicon_Iron_Helmet.png",              category: "Armor",     rarity: 6 },
  { id: "iron_chestplate",       name: "Iron Chestplate",          icon: "Invicon_Iron_Chestplate.png",          category: "Armor",     rarity: 6 },
  { id: "iron_leggings",         name: "Iron Leggings",            icon: "Invicon_Iron_Leggings.png",            category: "Armor",     rarity: 6 },
  { id: "iron_boots",            name: "Iron Boots",               icon: "Invicon_Iron_Boots.png",               category: "Armor",     rarity: 6 },
  { id: "iron_horse_armor",      name: "Iron Horse Armor",         icon: "Invicon_Iron_Horse_Armor.png",         category: "Armor",     rarity: 6 },
  { id: "copper_ingot",          name: "Copper Ingot",             icon: "Invicon_Copper_Ingot.png",             category: "Materials", rarity: 6 },
  { id: "raw_copper",            name: "Raw Copper",               icon: "Invicon_Raw_Copper.png",               category: "Materials", rarity: 6 },
  { id: "copper_block",          name: "Copper Block",             icon: "Invicon_Copper_Block.png",             category: "Blocks",    rarity: 6 },
  { id: "coal",                  name: "Coal",                     icon: "Invicon_Coal.png",                     category: "Materials", rarity: 6 },
  { id: "charcoal",              name: "Charcoal",                 icon: "Invicon_Charcoal.png",                 category: "Materials", rarity: 6 },
  { id: "coal_block",            name: "Block of Coal",            icon: "Invicon_Block_of_Coal.png",            category: "Blocks",    rarity: 6 },
  { id: "nether_brick",          name: "Nether Brick",             icon: "Invicon_Nether_Brick.png",             category: "Materials", rarity: 6 },
  { id: "nether_bricks",         name: "Nether Bricks",            icon: "Invicon_Nether_Bricks.png",            category: "Blocks",    rarity: 6 },
  { id: "shroomlight",           name: "Shroomlight",              icon: "Invicon_Shroomlight.png",              category: "Blocks",    rarity: 6 },
  { id: "leather",               name: "Leather",                  icon: "Invicon_Leather.png",                  category: "Materials", rarity: 6 },
  { id: "leather_helmet",        name: "Leather Helmet",           icon: "Invicon_Leather_Helmet.png",           category: "Armor",     rarity: 6 },
  { id: "leather_chestplate",    name: "Leather Chestplate",       icon: "Invicon_Leather_Chestplate.png",       category: "Armor",     rarity: 6 },
  { id: "leather_leggings",      name: "Leather Leggings",         icon: "Invicon_Leather_Leggings.png",         category: "Armor",     rarity: 6 },
  { id: "leather_boots",         name: "Leather Boots",            icon: "Invicon_Leather_Boots.png",            category: "Armor",     rarity: 6 },
  { id: "leather_horse_armor",   name: "Leather Horse Armor",      icon: "Invicon_Leather_Horse_Armor.png",      category: "Armor",     rarity: 6 },
  { id: "bone",                  name: "Bone",                     icon: "Invicon_Bone.png",                     category: "Materials", rarity: 6 },
  { id: "bone_meal",             name: "Bone Meal",                icon: "Invicon_Bone_Meal.png",                category: "Materials", rarity: 6 },
  { id: "bone_block",            name: "Bone Block",               icon: "Invicon_Bone_Block.png",               category: "Blocks",    rarity: 6 },
  { id: "feather",               name: "Feather",                  icon: "Invicon_Feather.png",                  category: "Materials", rarity: 6 },
  { id: "flint",                 name: "Flint",                    icon: "Invicon_Flint.png",                    category: "Materials", rarity: 6 },
  { id: "flint_and_steel",       name: "Flint and Steel",          icon: "Invicon_Flint_and_Steel.png",          category: "Tools",     rarity: 6 },
  { id: "shears",                name: "Shears",                   icon: "Invicon_Shears.png",                   category: "Tools",     rarity: 6 },
  { id: "fishing_rod",           name: "Fishing Rod",              icon: "Invicon_Fishing_Rod.png",              category: "Tools",     rarity: 6 },
  { id: "bucket",                name: "Bucket",                   icon: "Invicon_Bucket.png",                   category: "Tools",     rarity: 6 },
  { id: "water_bucket",          name: "Water Bucket",             icon: "Invicon_Water_Bucket.png",             category: "Tools",     rarity: 6 },
  { id: "lava_bucket",           name: "Lava Bucket",              icon: "Invicon_Lava_Bucket.png",              category: "Tools",     rarity: 6 },
  { id: "milk_bucket",           name: "Milk Bucket",              icon: "Invicon_Milk_Bucket.png",              category: "Tools",     rarity: 6 },
  { id: "powder_snow_bucket",    name: "Powder Snow Bucket",       icon: "Invicon_Powder_Snow_Bucket.png",       category: "Tools",     rarity: 6 },
  { id: "compass",               name: "Compass",                  icon: "Invicon_Compass.gif",                  category: "Tools",     rarity: 6 },
  { id: "clock",                 name: "Clock",                    icon: "Invicon_Clock.gif",                    category: "Tools",     rarity: 6 },
  { id: "map",                   name: "Map",                      icon: "Invicon_Map.png",                      category: "Tools",     rarity: 6 },
  { id: "book",                  name: "Book",                     icon: "Invicon_Book.png",                     category: "Enchanting",rarity: 6 },
  { id: "bookshelf",             name: "Bookshelf",                icon: "Invicon_Bookshelf.png",                category: "Enchanting",rarity: 6 },
  { id: "chiseled_bookshelf",    name: "Chiseled Bookshelf",       icon: "Invicon_Chiseled_Bookshelf.png",       category: "Enchanting",rarity: 6 },
  { id: "grindstone",            name: "Grindstone",               icon: "Invicon_Grindstone.png",               category: "Enchanting",rarity: 6 },
  { id: "anvil",                 name: "Anvil",                    icon: "Invicon_Anvil.png",                    category: "Blocks",    rarity: 6 },
  { id: "enchanting_table",      name: "Enchanting Table",         icon: "Invicon_Enchanting_Table.png",         category: "Blocks",    rarity: 6 },
  { id: "brewing_stand",         name: "Brewing Stand",            icon: "Invicon_Brewing_Stand.png",            category: "Blocks",    rarity: 6 },
  { id: "glass_bottle",          name: "Glass Bottle",             icon: "Invicon_Glass_Bottle.png",             category: "Potions",   rarity: 6 },
  { id: "arrow",                 name: "Arrow",                    icon: "Invicon_Arrow.png",                    category: "Combat",    rarity: 6 },
  { id: "honeycomb_block",       name: "Honeycomb Block",          icon: "Invicon_Honeycomb_Block.png",          category: "Blocks",    rarity: 6 },
  { id: "honey_block",           name: "Honey Block",              icon: "Invicon_Honey_Block.png",              category: "Blocks",    rarity: 6 },
  { id: "beehive",               name: "Beehive",                  icon: "Invicon_Beehive.png",                  category: "Blocks",    rarity: 6 },
  { id: "bee_nest",              name: "Bee Nest",                 icon: "Invicon_Bee_Nest.png",                 category: "Blocks",    rarity: 6 },
  { id: "carrot_on_a_stick",     name: "Carrot on a Stick",        icon: "Invicon_Carrot_on_a_Stick.png",        category: "Tools",     rarity: 6 },
  { id: "warped_fungus_stick",   name: "Warped Fungus on a Stick", icon: "Invicon_Warped_Fungus_on_a_Stick.png", category: "Tools",     rarity: 6 },
  { id: "dried_kelp",            name: "Dried Kelp",               icon: "Invicon_Dried_Kelp.png",               category: "Food",      rarity: 6 },
  { id: "dried_kelp_block",      name: "Dried Kelp Block",         icon: "Invicon_Dried_Kelp_Block.png",         category: "Blocks",    rarity: 6 },
  { id: "kelp",                  name: "Kelp",                     icon: "Invicon_Kelp.png",                     category: "Ocean",     rarity: 6 },

  // ── Rarity 7 — Common Crafted ──
  { id: "stone_sword",           name: "Stone Sword",              icon: "Invicon_Stone_Sword.png",              category: "Weapons",   rarity: 7 },
  { id: "stone_pickaxe",         name: "Stone Pickaxe",            icon: "Invicon_Stone_Pickaxe.png",            category: "Tools",     rarity: 7 },
  { id: "stone_axe",             name: "Stone Axe",                icon: "Invicon_Stone_Axe.png",                category: "Tools",     rarity: 7 },
  { id: "stone_shovel",          name: "Stone Shovel",             icon: "Invicon_Stone_Shovel.png",             category: "Tools",     rarity: 7 },
  { id: "stone_hoe",             name: "Stone Hoe",                icon: "Invicon_Stone_Hoe.png",                category: "Tools",     rarity: 7 },
  { id: "wooden_sword",          name: "Wooden Sword",             icon: "Invicon_Wooden_Sword.png",             category: "Weapons",   rarity: 7 },
  { id: "wooden_pickaxe",        name: "Wooden Pickaxe",           icon: "Invicon_Wooden_Pickaxe.png",           category: "Tools",     rarity: 7 },
  { id: "wooden_axe",            name: "Wooden Axe",               icon: "Invicon_Wooden_Axe.png",               category: "Tools",     rarity: 7 },
  { id: "wooden_shovel",         name: "Wooden Shovel",            icon: "Invicon_Wooden_Shovel.png",            category: "Tools",     rarity: 7 },
  { id: "wooden_hoe",            name: "Wooden Hoe",               icon: "Invicon_Wooden_Hoe.png",               category: "Tools",     rarity: 7 },
  { id: "chest",                 name: "Chest",                    icon: "Invicon_Chest.png",                    category: "Blocks",    rarity: 7 },
  { id: "trapped_chest",         name: "Trapped Chest",            icon: "Invicon_Trapped_Chest.png",            category: "Blocks",    rarity: 7 },
  { id: "barrel",                name: "Barrel",                   icon: "Invicon_Barrel.png",                   category: "Blocks",    rarity: 7 },
  { id: "ender_chest",           name: "Ender Chest",              icon: "Invicon_Ender_Chest.png",              category: "Blocks",    rarity: 7 },
  { id: "crafting_table",        name: "Crafting Table",           icon: "Invicon_Crafting_Table.png",           category: "Blocks",    rarity: 7 },
  { id: "furnace",               name: "Furnace",                  icon: "Invicon_Furnace.png",                  category: "Blocks",    rarity: 7 },
  { id: "blast_furnace",         name: "Blast Furnace",            icon: "Invicon_Blast_Furnace.png",            category: "Blocks",    rarity: 7 },
  { id: "smoker",                name: "Smoker",                   icon: "Invicon_Smoker.png",                   category: "Blocks",    rarity: 7 },
  { id: "campfire",              name: "Campfire",                 icon: "Invicon_Campfire.png",                 category: "Blocks",    rarity: 7 },
  { id: "soul_campfire",         name: "Soul Campfire",            icon: "Invicon_Soul_Campfire.png",            category: "Blocks",    rarity: 7 },
  { id: "hopper",                name: "Hopper",                   icon: "Invicon_Hopper.png",                   category: "Redstone",  rarity: 7 },
  { id: "dispenser",             name: "Dispenser",                icon: "Invicon_Dispenser.png",                category: "Redstone",  rarity: 7 },
  { id: "dropper",               name: "Dropper",                  icon: "Invicon_Dropper.png",                  category: "Redstone",  rarity: 7 },
  { id: "piston",                name: "Piston",                   icon: "Invicon_Piston.png",                   category: "Redstone",  rarity: 7 },
  { id: "sticky_piston",         name: "Sticky Piston",            icon: "Invicon_Sticky_Piston.png",            category: "Redstone",  rarity: 7 },
  { id: "observer",              name: "Observer",                 icon: "Invicon_Observer.png",                 category: "Redstone",  rarity: 7 },
  { id: "repeater",              name: "Redstone Repeater",        icon: "Invicon_Redstone_Repeater.png",        category: "Redstone",  rarity: 7 },
  { id: "comparator",            name: "Redstone Comparator",      icon: "Invicon_Redstone_Comparator.png",      category: "Redstone",  rarity: 7 },
  { id: "redstone_lamp",         name: "Redstone Lamp",            icon: "Invicon_Redstone_Lamp.png",            category: "Redstone",  rarity: 7 },
  { id: "redstone_torch",        name: "Redstone Torch",           icon: "Invicon_Redstone_Torch.png",           category: "Redstone",  rarity: 7 },
  { id: "daylight_detector",     name: "Daylight Detector",        icon: "Invicon_Daylight_Detector.png",        category: "Redstone",  rarity: 7 },
  { id: "target",                name: "Target",                   icon: "Invicon_Target.png",                   category: "Redstone",  rarity: 7 },
  { id: "lever",                 name: "Lever",                    icon: "Invicon_Lever.png",                    category: "Redstone",  rarity: 7 },
  { id: "tripwire_hook",         name: "Tripwire Hook",            icon: "Invicon_Tripwire_Hook.png",            category: "Redstone",  rarity: 7 },
  { id: "lightning_rod",         name: "Lightning Rod",            icon: "Invicon_Lightning_Rod.png",            category: "Blocks",    rarity: 7 },
  { id: "scaffolding",           name: "Scaffolding",              icon: "Invicon_Scaffolding.png",              category: "Blocks",    rarity: 7 },
  { id: "loom",                  name: "Loom",                     icon: "Invicon_Loom.png",                     category: "Blocks",    rarity: 7 },
  { id: "cartography_table",     name: "Cartography Table",        icon: "Invicon_Cartography_Table.png",        category: "Blocks",    rarity: 7 },
  { id: "fletching_table",       name: "Fletching Table",          icon: "Invicon_Fletching_Table.png",          category: "Blocks",    rarity: 7 },
  { id: "smithing_table",        name: "Smithing Table",           icon: "Invicon_Smithing_Table.png",           category: "Blocks",    rarity: 7 },
  { id: "stonecutter",           name: "Stonecutter",              icon: "Invicon_Stonecutter.gif",              category: "Blocks",    rarity: 7 },
  { id: "jukebox",               name: "Jukebox",                  icon: "Invicon_Jukebox.png",                  category: "Blocks",    rarity: 7 },
  { id: "note_block",            name: "Note Block",               icon: "Invicon_Note_Block.png",               category: "Blocks",    rarity: 7 },
  { id: "bell",                  name: "Bell",                     icon: "Invicon_Bell.png",                     category: "Blocks",    rarity: 7 },
  { id: "lantern",               name: "Lantern",                  icon: "Invicon_Lantern.png",                  category: "Blocks",    rarity: 7 },
  { id: "soul_lantern",          name: "Soul Lantern",             icon: "Invicon_Soul_Lantern.png",             category: "Blocks",    rarity: 7 },
  { id: "item_frame",            name: "Item Frame",               icon: "Invicon_Item_Frame.png",               category: "Blocks",    rarity: 7 },
  { id: "glow_item_frame",       name: "Glow Item Frame",          icon: "Invicon_Glow_Item_Frame.png",          category: "Blocks",    rarity: 7 },
  { id: "painting",              name: "Painting",                 icon: "Invicon_Painting.png",                 category: "Blocks",    rarity: 7 },
  { id: "armor_stand",           name: "Armor Stand",              icon: "Invicon_Armor_Stand.png",              category: "Blocks",    rarity: 7 },
  { id: "flower_pot",            name: "Flower Pot",               icon: "Invicon_Flower_Pot.png",               category: "Blocks",    rarity: 7 },
  { id: "cauldron",              name: "Cauldron",                 icon: "Invicon_Cauldron.png",                 category: "Blocks",    rarity: 7 },
  { id: "crafter",               name: "Crafter",                  icon: "Invicon_Crafter.png",                  category: "Blocks",    rarity: 7 },
  { id: "trial_spawner",         name: "Trial Spawner",            icon: "Invicon_Trial_Spawner.png",            category: "Blocks",    rarity: 7 },
  { id: "vault",                 name: "Vault",                    icon: "Invicon_Vault.png",                    category: "Blocks",    rarity: 7 },
  { id: "egg",                   name: "Egg",                      icon: "Invicon_Egg.png",                      category: "Materials", rarity: 7 },
  { id: "cooked_beef",           name: "Steak",                    icon: "Invicon_Cooked_Beef.png",              category: "Food",      rarity: 7 },
  { id: "cooked_porkchop",       name: "Cooked Porkchop",          icon: "Invicon_Cooked_Porkchop.png",          category: "Food",      rarity: 7 },
  { id: "cooked_chicken",        name: "Cooked Chicken",           icon: "Invicon_Cooked_Chicken.png",           category: "Food",      rarity: 7 },
  { id: "cooked_mutton",         name: "Cooked Mutton",            icon: "Invicon_Cooked_Mutton.png",            category: "Food",      rarity: 7 },
  { id: "cooked_rabbit",         name: "Cooked Rabbit",            icon: "Invicon_Cooked_Rabbit.png",            category: "Food",      rarity: 7 },
  { id: "cooked_cod",            name: "Cooked Cod",               icon: "Invicon_Cooked_Cod.png",               category: "Food",      rarity: 7 },
  { id: "cooked_salmon",         name: "Cooked Salmon",            icon: "Invicon_Cooked_Salmon.png",            category: "Food",      rarity: 7 },
  { id: "rabbit_stew",           name: "Rabbit Stew",              icon: "Invicon_Rabbit_Stew.png",              category: "Food",      rarity: 7 },
  { id: "mushroom_stew",         name: "Mushroom Stew",            icon: "Invicon_Mushroom_Stew.png",            category: "Food",      rarity: 7 },
  { id: "beetroot_soup",         name: "Beetroot Soup",            icon: "Invicon_Beetroot_Soup.png",            category: "Food",      rarity: 7 },
  { id: "baked_potato",          name: "Baked Potato",             icon: "Invicon_Baked_Potato.png",             category: "Food",      rarity: 7 },
  { id: "bread",                 name: "Bread",                    icon: "Invicon_Bread.png",                    category: "Food",      rarity: 7 },
  { id: "pumpkin_pie",           name: "Pumpkin Pie",              icon: "Invicon_Pumpkin_Pie.png",              category: "Food",      rarity: 7 },
  { id: "cookie",                name: "Cookie",                   icon: "Invicon_Cookie.png",                   category: "Food",      rarity: 7 },
  { id: "cake",                  name: "Cake",                     icon: "Invicon_Cake.png",                     category: "Food",      rarity: 7 },
  { id: "suspicious_stew",       name: "Suspicious Stew",          icon: "Invicon_Suspicious_Stew.png",          category: "Food",      rarity: 7 },

  // ── Rarity 8 — Very Common ──
  { id: "wheat",                 name: "Wheat",                    icon: "Invicon_Wheat.png",                    category: "Food",      rarity: 8 },
  { id: "apple",                 name: "Apple",                    icon: "Invicon_Apple.png",                    category: "Food",      rarity: 8 },
  { id: "carrot",                name: "Carrot",                   icon: "Invicon_Carrot.png",                   category: "Food",      rarity: 8 },
  { id: "potato",                name: "Potato",                   icon: "Invicon_Potato.png",                   category: "Food",      rarity: 8 },
  { id: "beetroot",              name: "Beetroot",                 icon: "Invicon_Beetroot.png",                 category: "Food",      rarity: 8 },
  { id: "beef",                  name: "Raw Beef",                 icon: "Invicon_Raw_Beef.png",                 category: "Food",      rarity: 8 },
  { id: "porkchop",              name: "Raw Porkchop",             icon: "Invicon_Raw_Porkchop.png",             category: "Food",      rarity: 8 },
  { id: "chicken",               name: "Raw Chicken",              icon: "Invicon_Raw_Chicken.png",              category: "Food",      rarity: 8 },
  { id: "mutton",                name: "Raw Mutton",               icon: "Invicon_Raw_Mutton.png",               category: "Food",      rarity: 8 },
  { id: "rabbit",                name: "Raw Rabbit",               icon: "Invicon_Raw_Rabbit.png",               category: "Food",      rarity: 8 },
  { id: "cod",                   name: "Raw Cod",                  icon: "Invicon_Raw_Cod.png",                  category: "Food",      rarity: 8 },
  { id: "salmon",                name: "Raw Salmon",               icon: "Invicon_Raw_Salmon.png",               category: "Food",      rarity: 8 },
  { id: "tropical_fish",         name: "Tropical Fish",            icon: "Invicon_Tropical_Fish.png",            category: "Food",      rarity: 8 },
  { id: "melon_slice",           name: "Melon Slice",              icon: "Invicon_Melon_Slice.png",              category: "Food",      rarity: 8 },
  { id: "poisonous_potato",      name: "Poisonous Potato",         icon: "Invicon_Poisonous_Potato.png",         category: "Food",      rarity: 8 },
  { id: "oak_log",               name: "Oak Log",                  icon: "Invicon_Oak_Log.png",                  category: "Wood",      rarity: 8 },
  { id: "spruce_log",            name: "Spruce Log",               icon: "Invicon_Spruce_Log.png",               category: "Wood",      rarity: 8 },
  { id: "birch_log",             name: "Birch Log",                icon: "Invicon_Birch_Log.png",                category: "Wood",      rarity: 8 },
  { id: "jungle_log",            name: "Jungle Log",               icon: "Invicon_Jungle_Log.png",               category: "Wood",      rarity: 8 },
  { id: "acacia_log",            name: "Acacia Log",               icon: "Invicon_Acacia_Log.png",               category: "Wood",      rarity: 8 },
  { id: "dark_oak_log",          name: "Dark Oak Log",             icon: "Invicon_Dark_Oak_Log.png",             category: "Wood",      rarity: 8 },
  { id: "mangrove_log",          name: "Mangrove Log",             icon: "Invicon_Mangrove_Log.png",             category: "Wood",      rarity: 8 },
  { id: "cherry_log",            name: "Cherry Log",               icon: "Invicon_Cherry_Log.png",               category: "Wood",      rarity: 8 },
  { id: "bamboo_block",          name: "Bamboo Block",             icon: "Invicon_Bamboo_Block.png",             category: "Wood",      rarity: 8 },
  { id: "oak_planks",            name: "Oak Planks",               icon: "Invicon_Oak_Planks.png",               category: "Wood",      rarity: 8 },
  { id: "spruce_planks",         name: "Spruce Planks",            icon: "Invicon_Spruce_Planks.png",            category: "Wood",      rarity: 8 },
  { id: "birch_planks",          name: "Birch Planks",             icon: "Invicon_Birch_Planks.png",             category: "Wood",      rarity: 8 },
  { id: "jungle_planks",         name: "Jungle Planks",            icon: "Invicon_Jungle_Planks.png",            category: "Wood",      rarity: 8 },
  { id: "acacia_planks",         name: "Acacia Planks",            icon: "Invicon_Acacia_Planks.png",            category: "Wood",      rarity: 8 },
  { id: "dark_oak_planks",       name: "Dark Oak Planks",          icon: "Invicon_Dark_Oak_Planks.png",          category: "Wood",      rarity: 8 },
  { id: "mangrove_planks",       name: "Mangrove Planks",          icon: "Invicon_Mangrove_Planks.png",          category: "Wood",      rarity: 8 },
  { id: "cherry_planks",         name: "Cherry Planks",            icon: "Invicon_Cherry_Planks.png",            category: "Wood",      rarity: 8 },
  { id: "bamboo_planks",         name: "Bamboo Planks",            icon: "Invicon_Bamboo_Planks.png",            category: "Wood",      rarity: 8 },
  { id: "crimson_planks",        name: "Crimson Planks",           icon: "Invicon_Crimson_Planks.png",           category: "Wood",      rarity: 8 },
  { id: "warped_planks",         name: "Warped Planks",            icon: "Invicon_Warped_Planks.png",            category: "Wood",      rarity: 8 },
  { id: "oak_stairs",            name: "Oak Stairs",               icon: "Invicon_Oak_Stairs.png",               category: "Wood",      rarity: 8 },
  { id: "spruce_stairs",         name: "Spruce Stairs",            icon: "Invicon_Spruce_Stairs.png",            category: "Wood",      rarity: 8 },
  { id: "birch_stairs",          name: "Birch Stairs",             icon: "Invicon_Birch_Stairs.png",             category: "Wood",      rarity: 8 },
  { id: "jungle_stairs",         name: "Jungle Stairs",            icon: "Invicon_Jungle_Stairs.png",            category: "Wood",      rarity: 8 },
  { id: "acacia_stairs",         name: "Acacia Stairs",            icon: "Invicon_Acacia_Stairs.png",            category: "Wood",      rarity: 8 },
  { id: "dark_oak_stairs",       name: "Dark Oak Stairs",          icon: "Invicon_Dark_Oak_Stairs.png",          category: "Wood",      rarity: 8 },
  { id: "mangrove_stairs",       name: "Mangrove Stairs",          icon: "Invicon_Mangrove_Stairs.png",          category: "Wood",      rarity: 8 },
  { id: "cherry_stairs",         name: "Cherry Stairs",            icon: "Invicon_Cherry_Stairs.png",            category: "Wood",      rarity: 8 },
  { id: "bamboo_stairs",         name: "Bamboo Stairs",            icon: "Invicon_Bamboo_Stairs.png",            category: "Wood",      rarity: 8 },
  { id: "crimson_stairs",        name: "Crimson Stairs",           icon: "Invicon_Crimson_Stairs.png",           category: "Wood",      rarity: 8 },
  { id: "warped_stairs",         name: "Warped Stairs",            icon: "Invicon_Warped_Stairs.png",            category: "Wood",      rarity: 8 },
  { id: "stone_stairs",          name: "Stone Stairs",             icon: "Invicon_Stone_Stairs.png",             category: "Blocks",    rarity: 8 },
  { id: "cobblestone_stairs",    name: "Cobblestone Stairs",       icon: "Invicon_Cobblestone_Stairs.png",       category: "Blocks",    rarity: 8 },
  { id: "stone_brick_stairs",    name: "Stone Brick Stairs",       icon: "Invicon_Stone_Brick_Stairs.png",       category: "Blocks",    rarity: 8 },
  { id: "sandstone_stairs",      name: "Sandstone Stairs",         icon: "Invicon_Sandstone_Stairs.png",         category: "Blocks",    rarity: 8 },
  { id: "nether_brick_stairs",   name: "Nether Brick Stairs",      icon: "Invicon_Nether_Brick_Stairs.png",      category: "Blocks",    rarity: 8 },
  { id: "blackstone_stairs",     name: "Blackstone Stairs",        icon: "Invicon_Blackstone_Stairs.png",        category: "Blocks",    rarity: 8 },
  { id: "deepslate_brick_stairs",name: "Deepslate Brick Stairs",   icon: "Invicon_Deepslate_Brick_Stairs.png",   category: "Blocks",    rarity: 8 },
  { id: "stone",                 name: "Stone",                    icon: "Invicon_Stone.png",                    category: "Blocks",    rarity: 8 },
  { id: "cobblestone",           name: "Cobblestone",              icon: "Invicon_Cobblestone.png",              category: "Blocks",    rarity: 8 },
  { id: "stone_bricks",          name: "Stone Bricks",             icon: "Invicon_Stone_Bricks.png",             category: "Blocks",    rarity: 8 },
  { id: "granite",               name: "Granite",                  icon: "Invicon_Granite.png",                  category: "Blocks",    rarity: 8 },
  { id: "polished_granite",      name: "Polished Granite",         icon: "Invicon_Polished_Granite.png",         category: "Blocks",    rarity: 8 },
  { id: "diorite",               name: "Diorite",                  icon: "Invicon_Diorite.png",                  category: "Blocks",    rarity: 8 },
  { id: "polished_diorite",      name: "Polished Diorite",         icon: "Invicon_Polished_Diorite.png",         category: "Blocks",    rarity: 8 },
  { id: "andesite",              name: "Andesite",                 icon: "Invicon_Andesite.png",                 category: "Blocks",    rarity: 8 },
  { id: "polished_andesite",     name: "Polished Andesite",        icon: "Invicon_Polished_Andesite.png",        category: "Blocks",    rarity: 8 },
  { id: "deepslate",             name: "Deepslate",                icon: "Invicon_Deepslate.png",                category: "Blocks",    rarity: 8 },
  { id: "cobbled_deepslate",     name: "Cobbled Deepslate",        icon: "Invicon_Cobbled_Deepslate.png",        category: "Blocks",    rarity: 8 },
  { id: "tuff",                  name: "Tuff",                     icon: "Invicon_Tuff.png",                     category: "Blocks",    rarity: 8 },
  { id: "tuff_bricks",           name: "Tuff Bricks",              icon: "Invicon_Tuff_Bricks.png",              category: "Blocks",    rarity: 8 },
  { id: "calcite",               name: "Calcite",                  icon: "Invicon_Calcite.png",                  category: "Blocks",    rarity: 8 },
  { id: "sandstone",             name: "Sandstone",                icon: "Invicon_Sandstone.png",                category: "Blocks",    rarity: 8 },
  { id: "red_sandstone",         name: "Red Sandstone",            icon: "Invicon_Red_Sandstone.png",            category: "Blocks",    rarity: 8 },
  { id: "bricks",                name: "Bricks",                   icon: "Invicon_Bricks.png",                   category: "Blocks",    rarity: 8 },
  { id: "brick",                 name: "Brick",                    icon: "Invicon_Brick.png",                    category: "Materials", rarity: 8 },
  { id: "mud_bricks",            name: "Mud Bricks",               icon: "Invicon_Mud_Bricks.png",               category: "Blocks",    rarity: 8 },
  { id: "netherrack",            name: "Netherrack",               icon: "Invicon_Netherrack.png",               category: "Blocks",    rarity: 8 },
  { id: "soul_sand",             name: "Soul Sand",                icon: "Invicon_Soul_Sand.png",                category: "Blocks",    rarity: 8 },
  { id: "basalt",                name: "Basalt",                   icon: "Invicon_Basalt.png",                   category: "Blocks",    rarity: 8 },
  { id: "blackstone",            name: "Blackstone",               icon: "Invicon_Blackstone.png",               category: "Blocks",    rarity: 8 },
  { id: "end_stone",             name: "End Stone",                icon: "Invicon_End_Stone.png",                category: "Blocks",    rarity: 8 },
  { id: "purpur_block",          name: "Purpur Block",             icon: "Invicon_Purpur_Block.png",             category: "Blocks",    rarity: 8 },
  { id: "glass",                 name: "Glass",                    icon: "Invicon_Glass.png",                    category: "Blocks",    rarity: 8 },
  { id: "glass_pane",            name: "Glass Pane",               icon: "Invicon_Glass_Pane.png",               category: "Blocks",    rarity: 8 },
  { id: "torch",                 name: "Torch",                    icon: "Invicon_Torch.png",                    category: "Blocks",    rarity: 8 },
  { id: "soul_torch",            name: "Soul Torch",               icon: "Invicon_Soul_Torch.png",               category: "Blocks",    rarity: 8 },
  { id: "cactus",                name: "Cactus",                   icon: "Invicon_Cactus.png",                   category: "Plants",    rarity: 8 },
  { id: "sugar_cane",            name: "Sugar Cane",               icon: "Invicon_Sugar_Cane.png",               category: "Plants",    rarity: 8 },
  { id: "bamboo",                name: "Bamboo",                   icon: "Invicon_Bamboo.png",                   category: "Plants",    rarity: 8 },
  { id: "pumpkin",               name: "Pumpkin",                  icon: "Invicon_Pumpkin.png",                  category: "Plants",    rarity: 8 },
  { id: "melon",                 name: "Melon",                    icon: "Invicon_Melon.png",                    category: "Plants",    rarity: 8 },
  { id: "brown_mushroom",        name: "Brown Mushroom",           icon: "Invicon_Brown_Mushroom.png",           category: "Plants",    rarity: 8 },
  { id: "red_mushroom",          name: "Red Mushroom",             icon: "Invicon_Red_Mushroom.png",             category: "Plants",    rarity: 8 },
  { id: "dandelion",             name: "Dandelion",                icon: "Invicon_Dandelion.png",                category: "Plants",    rarity: 8 },
  { id: "poppy",                 name: "Poppy",                    icon: "Invicon_Poppy.png",                    category: "Plants",    rarity: 8 },
  { id: "wither_rose",           name: "Wither Rose",              icon: "Invicon_Wither_Rose.png",              category: "Plants",    rarity: 8 },
  { id: "torchflower",           name: "Torchflower",              icon: "Invicon_Torchflower.png",              category: "Plants",    rarity: 8 },
  { id: "white_wool",            name: "White Wool",               icon: "Invicon_White_Wool.png",               category: "Wool",      rarity: 8 },
  { id: "orange_wool",           name: "Orange Wool",              icon: "Invicon_Orange_Wool.png",              category: "Wool",      rarity: 8 },
  { id: "magenta_wool",          name: "Magenta Wool",             icon: "Invicon_Magenta_Wool.png",             category: "Wool",      rarity: 8 },
  { id: "light_blue_wool",       name: "Light Blue Wool",          icon: "Invicon_Light_Blue_Wool.png",          category: "Wool",      rarity: 8 },
  { id: "yellow_wool",           name: "Yellow Wool",              icon: "Invicon_Yellow_Wool.png",              category: "Wool",      rarity: 8 },
  { id: "lime_wool",             name: "Lime Wool",                icon: "Invicon_Lime_Wool.png",                category: "Wool",      rarity: 8 },
  { id: "pink_wool",             name: "Pink Wool",                icon: "Invicon_Pink_Wool.png",                category: "Wool",      rarity: 8 },
  { id: "gray_wool",             name: "Gray Wool",                icon: "Invicon_Gray_Wool.png",                category: "Wool",      rarity: 8 },
  { id: "cyan_wool",             name: "Cyan Wool",                icon: "Invicon_Cyan_Wool.png",                category: "Wool",      rarity: 8 },
  { id: "purple_wool",           name: "Purple Wool",              icon: "Invicon_Purple_Wool.png",              category: "Wool",      rarity: 8 },
  { id: "blue_wool",             name: "Blue Wool",                icon: "Invicon_Blue_Wool.png",                category: "Wool",      rarity: 8 },
  { id: "brown_wool",            name: "Brown Wool",               icon: "Invicon_Brown_Wool.png",               category: "Wool",      rarity: 8 },
  { id: "green_wool",            name: "Green Wool",               icon: "Invicon_Green_Wool.png",               category: "Wool",      rarity: 8 },
  { id: "red_wool",              name: "Red Wool",                 icon: "Invicon_Red_Wool.png",                 category: "Wool",      rarity: 8 },
  { id: "black_wool",            name: "Black Wool",               icon: "Invicon_Black_Wool.png",               category: "Wool",      rarity: 8 },
  { id: "terracotta",            name: "Terracotta",               icon: "Invicon_Terracotta.png",               category: "Blocks",    rarity: 8 },
  { id: "white_terracotta",      name: "White Terracotta",         icon: "Invicon_White_Terracotta.png",         category: "Blocks",    rarity: 8 },
  { id: "white_concrete",        name: "White Concrete",           icon: "Invicon_White_Concrete.png",           category: "Blocks",    rarity: 8 },
  { id: "orange_concrete",       name: "Orange Concrete",          icon: "Invicon_Orange_Concrete.png",          category: "Blocks",    rarity: 8 },
  { id: "prismarine",            name: "Prismarine",               icon: "Invicon_Prismarine.png",               category: "Blocks",    rarity: 8 },
  { id: "dark_prismarine",       name: "Dark Prismarine",          icon: "Invicon_Dark_Prismarine.png",          category: "Blocks",    rarity: 8 },
];

export function mcItemIconUrl(itemOrId: McItem | string): string {
  if (typeof itemOrId === "string") {
    const found = MC_ITEMS.find((i) => i.id === itemOrId);
    if (found) return `${BASE}${found.icon}`;
    const pascal = itemOrId.split("_").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join("_");
    return `${BASE}Invicon_${pascal}.png`;
  }
  return `${BASE}${itemOrId.icon}`;
}

export function searchMcItems(query: string): McItem[] {
  const q = query.toLowerCase().trim();
  if (!q) return [...MC_ITEMS].sort((a, b) => a.rarity - b.rarity).slice(0, 20);
  return MC_ITEMS
    .filter(
      (item) =>
        item.name.toLowerCase().includes(q) ||
        item.id.toLowerCase().includes(q) ||
        item.category.toLowerCase().includes(q),
    )
    .sort((a, b) => {
      const aStart = a.name.toLowerCase().startsWith(q) ? 0 : 1;
      const bStart = b.name.toLowerCase().startsWith(q) ? 0 : 1;
      if (aStart !== bStart) return aStart - bStart;
      return a.rarity - b.rarity;
    })
    .slice(0, 20);
}
