export type McItem = {
  id: string;
  name: string;
  category: string;
};

export function mcItemIconUrl(itemId: string): string {
  const pascal = itemId
    .split("_")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("_");
  return `https://minecraft.wiki/images/Invicon_${pascal}.png`;
}

// Full Minecraft 1.21.1 item list
export const MC_ITEMS: McItem[] = [
  // ── Netherite ──
  { id: "netherite_ingot", name: "Netherite Ingot", category: "Materials" },
  { id: "netherite_scrap", name: "Netherite Scrap", category: "Materials" },
  { id: "netherite_block", name: "Block of Netherite", category: "Blocks" },
  { id: "netherite_sword", name: "Netherite Sword", category: "Weapons" },
  { id: "netherite_pickaxe", name: "Netherite Pickaxe", category: "Tools" },
  { id: "netherite_axe", name: "Netherite Axe", category: "Tools" },
  { id: "netherite_shovel", name: "Netherite Shovel", category: "Tools" },
  { id: "netherite_hoe", name: "Netherite Hoe", category: "Tools" },
  { id: "netherite_helmet", name: "Netherite Helmet", category: "Armor" },
  { id: "netherite_chestplate", name: "Netherite Chestplate", category: "Armor" },
  { id: "netherite_leggings", name: "Netherite Leggings", category: "Armor" },
  { id: "netherite_boots", name: "Netherite Boots", category: "Armor" },
  { id: "netherite_upgrade_smithing_template", name: "Netherite Upgrade Template", category: "Materials" },

  // ── Diamond ──
  { id: "diamond", name: "Diamond", category: "Materials" },
  { id: "diamond_block", name: "Block of Diamond", category: "Blocks" },
  { id: "diamond_sword", name: "Diamond Sword", category: "Weapons" },
  { id: "diamond_pickaxe", name: "Diamond Pickaxe", category: "Tools" },
  { id: "diamond_axe", name: "Diamond Axe", category: "Tools" },
  { id: "diamond_shovel", name: "Diamond Shovel", category: "Tools" },
  { id: "diamond_hoe", name: "Diamond Hoe", category: "Tools" },
  { id: "diamond_helmet", name: "Diamond Helmet", category: "Armor" },
  { id: "diamond_chestplate", name: "Diamond Chestplate", category: "Armor" },
  { id: "diamond_leggings", name: "Diamond Leggings", category: "Armor" },
  { id: "diamond_boots", name: "Diamond Boots", category: "Armor" },

  // ── Gold ──
  { id: "gold_ingot", name: "Gold Ingot", category: "Materials" },
  { id: "gold_nugget", name: "Gold Nugget", category: "Materials" },
  { id: "gold_block", name: "Block of Gold", category: "Blocks" },
  { id: "raw_gold", name: "Raw Gold", category: "Materials" },
  { id: "raw_gold_block", name: "Raw Gold Block", category: "Blocks" },
  { id: "golden_sword", name: "Golden Sword", category: "Weapons" },
  { id: "golden_pickaxe", name: "Golden Pickaxe", category: "Tools" },
  { id: "golden_axe", name: "Golden Axe", category: "Tools" },
  { id: "golden_shovel", name: "Golden Shovel", category: "Tools" },
  { id: "golden_hoe", name: "Golden Hoe", category: "Tools" },
  { id: "golden_helmet", name: "Golden Helmet", category: "Armor" },
  { id: "golden_chestplate", name: "Golden Chestplate", category: "Armor" },
  { id: "golden_leggings", name: "Golden Leggings", category: "Armor" },
  { id: "golden_boots", name: "Golden Boots", category: "Armor" },
  { id: "golden_apple", name: "Golden Apple", category: "Food" },
  { id: "enchanted_golden_apple", name: "Enchanted Golden Apple", category: "Food" },
  { id: "golden_carrot", name: "Golden Carrot", category: "Food" },

  // ── Iron ──
  { id: "iron_ingot", name: "Iron Ingot", category: "Materials" },
  { id: "iron_nugget", name: "Iron Nugget", category: "Materials" },
  { id: "iron_block", name: "Block of Iron", category: "Blocks" },
  { id: "raw_iron", name: "Raw Iron", category: "Materials" },
  { id: "raw_iron_block", name: "Raw Iron Block", category: "Blocks" },
  { id: "iron_sword", name: "Iron Sword", category: "Weapons" },
  { id: "iron_pickaxe", name: "Iron Pickaxe", category: "Tools" },
  { id: "iron_axe", name: "Iron Axe", category: "Tools" },
  { id: "iron_shovel", name: "Iron Shovel", category: "Tools" },
  { id: "iron_hoe", name: "Iron Hoe", category: "Tools" },
  { id: "iron_helmet", name: "Iron Helmet", category: "Armor" },
  { id: "iron_chestplate", name: "Iron Chestplate", category: "Armor" },
  { id: "iron_leggings", name: "Iron Leggings", category: "Armor" },
  { id: "iron_boots", name: "Iron Boots", category: "Armor" },

  // ── Copper ──
  { id: "copper_ingot", name: "Copper Ingot", category: "Materials" },
  { id: "raw_copper", name: "Raw Copper", category: "Materials" },
  { id: "raw_copper_block", name: "Raw Copper Block", category: "Blocks" },
  { id: "copper_block", name: "Copper Block", category: "Blocks" },
  { id: "exposed_copper", name: "Exposed Copper", category: "Blocks" },
  { id: "weathered_copper", name: "Weathered Copper", category: "Blocks" },
  { id: "oxidized_copper", name: "Oxidized Copper", category: "Blocks" },
  { id: "waxed_copper_block", name: "Waxed Copper Block", category: "Blocks" },
  { id: "copper_bulb", name: "Copper Bulb", category: "Blocks" },
  { id: "copper_grate", name: "Copper Grate", category: "Blocks" },
  { id: "copper_door", name: "Copper Door", category: "Blocks" },
  { id: "copper_trapdoor", name: "Copper Trapdoor", category: "Blocks" },

  // ── Stone tools ──
  { id: "stone_sword", name: "Stone Sword", category: "Weapons" },
  { id: "stone_pickaxe", name: "Stone Pickaxe", category: "Tools" },
  { id: "stone_axe", name: "Stone Axe", category: "Tools" },
  { id: "stone_shovel", name: "Stone Shovel", category: "Tools" },
  { id: "stone_hoe", name: "Stone Hoe", category: "Tools" },

  // ── Wooden tools ──
  { id: "wooden_sword", name: "Wooden Sword", category: "Weapons" },
  { id: "wooden_pickaxe", name: "Wooden Pickaxe", category: "Tools" },
  { id: "wooden_axe", name: "Wooden Axe", category: "Tools" },
  { id: "wooden_shovel", name: "Wooden Shovel", category: "Tools" },
  { id: "wooden_hoe", name: "Wooden Hoe", category: "Tools" },

  // ── Leather armor ──
  { id: "leather_helmet", name: "Leather Helmet", category: "Armor" },
  { id: "leather_chestplate", name: "Leather Chestplate", category: "Armor" },
  { id: "leather_leggings", name: "Leather Leggings", category: "Armor" },
  { id: "leather_boots", name: "Leather Boots", category: "Armor" },
  { id: "leather_horse_armor", name: "Leather Horse Armor", category: "Armor" },
  { id: "iron_horse_armor", name: "Iron Horse Armor", category: "Armor" },
  { id: "golden_horse_armor", name: "Golden Horse Armor", category: "Armor" },
  { id: "diamond_horse_armor", name: "Diamond Horse Armor", category: "Armor" },

  // ── Emerald ──
  { id: "emerald", name: "Emerald", category: "Materials" },
  { id: "emerald_block", name: "Block of Emerald", category: "Blocks" },

  // ── Redstone ──
  { id: "redstone", name: "Redstone Dust", category: "Materials" },
  { id: "redstone_block", name: "Block of Redstone", category: "Blocks" },
  { id: "redstone_torch", name: "Redstone Torch", category: "Redstone" },
  { id: "redstone_lamp", name: "Redstone Lamp", category: "Redstone" },
  { id: "repeater", name: "Redstone Repeater", category: "Redstone" },
  { id: "comparator", name: "Redstone Comparator", category: "Redstone" },
  { id: "piston", name: "Piston", category: "Redstone" },
  { id: "sticky_piston", name: "Sticky Piston", category: "Redstone" },
  { id: "observer", name: "Observer", category: "Redstone" },
  { id: "dispenser", name: "Dispenser", category: "Redstone" },
  { id: "dropper", name: "Dropper", category: "Redstone" },
  { id: "hopper", name: "Hopper", category: "Redstone" },
  { id: "lever", name: "Lever", category: "Redstone" },
  { id: "daylight_detector", name: "Daylight Detector", category: "Redstone" },
  { id: "tripwire_hook", name: "Tripwire Hook", category: "Redstone" },
  { id: "target", name: "Target", category: "Redstone" },

  // ── Lapis ──
  { id: "lapis_lazuli", name: "Lapis Lazuli", category: "Materials" },
  { id: "lapis_block", name: "Lapis Lazuli Block", category: "Blocks" },

  // ── Quartz ──
  { id: "quartz", name: "Nether Quartz", category: "Materials" },
  { id: "quartz_block", name: "Block of Quartz", category: "Blocks" },

  // ── Coal ──
  { id: "coal", name: "Coal", category: "Materials" },
  { id: "charcoal", name: "Charcoal", category: "Materials" },
  { id: "coal_block", name: "Block of Coal", category: "Blocks" },

  // ── Amethyst ──
  { id: "amethyst_shard", name: "Amethyst Shard", category: "Materials" },
  { id: "amethyst_block", name: "Block of Amethyst", category: "Blocks" },
  { id: "budding_amethyst", name: "Budding Amethyst", category: "Blocks" },
  { id: "amethyst_cluster", name: "Amethyst Cluster", category: "Blocks" },
  { id: "spyglass", name: "Spyglass", category: "Tools" },

  // ── End / Ender ──
  { id: "ender_pearl", name: "Ender Pearl", category: "Materials" },
  { id: "eye_of_ender", name: "Eye of Ender", category: "Materials" },
  { id: "end_crystal", name: "End Crystal", category: "Combat" },
  { id: "elytra", name: "Elytra", category: "Armor" },
  { id: "shulker_shell", name: "Shulker Shell", category: "Materials" },
  { id: "shulker_box", name: "Shulker Box", category: "Blocks" },
  { id: "white_shulker_box", name: "White Shulker Box", category: "Blocks" },
  { id: "orange_shulker_box", name: "Orange Shulker Box", category: "Blocks" },
  { id: "magenta_shulker_box", name: "Magenta Shulker Box", category: "Blocks" },
  { id: "light_blue_shulker_box", name: "Light Blue Shulker Box", category: "Blocks" },
  { id: "yellow_shulker_box", name: "Yellow Shulker Box", category: "Blocks" },
  { id: "lime_shulker_box", name: "Lime Shulker Box", category: "Blocks" },
  { id: "pink_shulker_box", name: "Pink Shulker Box", category: "Blocks" },
  { id: "gray_shulker_box", name: "Gray Shulker Box", category: "Blocks" },
  { id: "light_gray_shulker_box", name: "Light Gray Shulker Box", category: "Blocks" },
  { id: "cyan_shulker_box", name: "Cyan Shulker Box", category: "Blocks" },
  { id: "purple_shulker_box", name: "Purple Shulker Box", category: "Blocks" },
  { id: "blue_shulker_box", name: "Blue Shulker Box", category: "Blocks" },
  { id: "brown_shulker_box", name: "Brown Shulker Box", category: "Blocks" },
  { id: "green_shulker_box", name: "Green Shulker Box", category: "Blocks" },
  { id: "red_shulker_box", name: "Red Shulker Box", category: "Blocks" },
  { id: "black_shulker_box", name: "Black Shulker Box", category: "Blocks" },
  { id: "end_stone", name: "End Stone", category: "Blocks" },
  { id: "end_stone_bricks", name: "End Stone Bricks", category: "Blocks" },
  { id: "purpur_block", name: "Purpur Block", category: "Blocks" },
  { id: "purpur_pillar", name: "Purpur Pillar", category: "Blocks" },
  { id: "chorus_fruit", name: "Chorus Fruit", category: "Food" },
  { id: "popped_chorus_fruit", name: "Popped Chorus Fruit", category: "Materials" },
  { id: "chorus_plant", name: "Chorus Plant", category: "Blocks" },
  { id: "chorus_flower", name: "Chorus Flower", category: "Blocks" },
  { id: "dragon_egg", name: "Dragon Egg", category: "Blocks" },
  { id: "dragon_breath", name: "Dragon's Breath", category: "Materials" },
  { id: "dragon_head", name: "Dragon Head", category: "Blocks" },

  // ── Nether ──
  { id: "ancient_debris", name: "Ancient Debris", category: "Materials" },
  { id: "blaze_rod", name: "Blaze Rod", category: "Materials" },
  { id: "blaze_powder", name: "Blaze Powder", category: "Materials" },
  { id: "ghast_tear", name: "Ghast Tear", category: "Materials" },
  { id: "magma_cream", name: "Magma Cream", category: "Materials" },
  { id: "nether_star", name: "Nether Star", category: "Materials" },
  { id: "nether_brick", name: "Nether Brick", category: "Materials" },
  { id: "nether_bricks", name: "Nether Bricks", category: "Blocks" },
  { id: "red_nether_bricks", name: "Red Nether Bricks", category: "Blocks" },
  { id: "cracked_nether_bricks", name: "Cracked Nether Bricks", category: "Blocks" },
  { id: "chiseled_nether_bricks", name: "Chiseled Nether Bricks", category: "Blocks" },
  { id: "nether_wart", name: "Nether Wart", category: "Materials" },
  { id: "nether_wart_block", name: "Nether Wart Block", category: "Blocks" },
  { id: "warped_wart_block", name: "Warped Wart Block", category: "Blocks" },
  { id: "shroomlight", name: "Shroomlight", category: "Blocks" },
  { id: "crying_obsidian", name: "Crying Obsidian", category: "Blocks" },
  { id: "obsidian", name: "Obsidian", category: "Blocks" },
  { id: "beacon", name: "Beacon", category: "Blocks" },
  { id: "glowstone", name: "Glowstone", category: "Blocks" },
  { id: "glowstone_dust", name: "Glowstone Dust", category: "Materials" },
  { id: "soul_sand", name: "Soul Sand", category: "Blocks" },
  { id: "soul_soil", name: "Soul Soil", category: "Blocks" },
  { id: "basalt", name: "Basalt", category: "Blocks" },
  { id: "blackstone", name: "Blackstone", category: "Blocks" },
  { id: "gilded_blackstone", name: "Gilded Blackstone", category: "Blocks" },
  { id: "magma_block", name: "Magma Block", category: "Blocks" },
  { id: "netherrack", name: "Netherrack", category: "Blocks" },
  { id: "crimson_stem", name: "Crimson Stem", category: "Blocks" },
  { id: "warped_stem", name: "Warped Stem", category: "Blocks" },
  { id: "crimson_planks", name: "Crimson Planks", category: "Blocks" },
  { id: "warped_planks", name: "Warped Planks", category: "Blocks" },

  // ── Smithing Templates ──
  { id: "coast_armor_trim_smithing_template", name: "Coast Armor Trim", category: "Smithing" },
  { id: "dune_armor_trim_smithing_template", name: "Dune Armor Trim", category: "Smithing" },
  { id: "eye_armor_trim_smithing_template", name: "Eye Armor Trim", category: "Smithing" },
  { id: "host_armor_trim_smithing_template", name: "Host Armor Trim", category: "Smithing" },
  { id: "raiser_armor_trim_smithing_template", name: "Raiser Armor Trim", category: "Smithing" },
  { id: "rib_armor_trim_smithing_template", name: "Rib Armor Trim", category: "Smithing" },
  { id: "sentry_armor_trim_smithing_template", name: "Sentry Armor Trim", category: "Smithing" },
  { id: "shaper_armor_trim_smithing_template", name: "Shaper Armor Trim", category: "Smithing" },
  { id: "silence_armor_trim_smithing_template", name: "Silence Armor Trim", category: "Smithing" },
  { id: "snout_armor_trim_smithing_template", name: "Snout Armor Trim", category: "Smithing" },
  { id: "spire_armor_trim_smithing_template", name: "Spire Armor Trim", category: "Smithing" },
  { id: "tide_armor_trim_smithing_template", name: "Tide Armor Trim", category: "Smithing" },
  { id: "vex_armor_trim_smithing_template", name: "Vex Armor Trim", category: "Smithing" },
  { id: "ward_armor_trim_smithing_template", name: "Ward Armor Trim", category: "Smithing" },
  { id: "wayfinder_armor_trim_smithing_template", name: "Wayfinder Armor Trim", category: "Smithing" },
  { id: "wild_armor_trim_smithing_template", name: "Wild Armor Trim", category: "Smithing" },
  { id: "bolt_armor_trim_smithing_template", name: "Bolt Armor Trim", category: "Smithing" },
  { id: "flow_armor_trim_smithing_template", name: "Flow Armor Trim", category: "Smithing" },

  // ── Enchanting ──
  { id: "enchanted_book", name: "Enchanted Book", category: "Enchanting" },
  { id: "book", name: "Book", category: "Enchanting" },
  { id: "bookshelf", name: "Bookshelf", category: "Enchanting" },
  { id: "chiseled_bookshelf", name: "Chiseled Bookshelf", category: "Enchanting" },
  { id: "experience_bottle", name: "Bottle o' Enchanting", category: "Enchanting" },
  { id: "grindstone", name: "Grindstone", category: "Enchanting" },
  { id: "anvil", name: "Anvil", category: "Blocks" },

  // ── Potions ──
  { id: "potion", name: "Potion", category: "Potions" },
  { id: "splash_potion", name: "Splash Potion", category: "Potions" },
  { id: "lingering_potion", name: "Lingering Potion", category: "Potions" },
  { id: "glass_bottle", name: "Glass Bottle", category: "Potions" },
  { id: "fermented_spider_eye", name: "Fermented Spider Eye", category: "Potions" },
  { id: "spider_eye", name: "Spider Eye", category: "Materials" },
  { id: "glistering_melon_slice", name: "Glistering Melon Slice", category: "Potions" },
  { id: "rabbit_foot", name: "Rabbit's Foot", category: "Potions" },
  { id: "pufferfish", name: "Pufferfish", category: "Potions" },

  // ── Food ──
  { id: "apple", name: "Apple", category: "Food" },
  { id: "bread", name: "Bread", category: "Food" },
  { id: "wheat", name: "Wheat", category: "Food" },
  { id: "cookie", name: "Cookie", category: "Food" },
  { id: "cake", name: "Cake", category: "Food" },
  { id: "pumpkin_pie", name: "Pumpkin Pie", category: "Food" },
  { id: "beef", name: "Raw Beef", category: "Food" },
  { id: "cooked_beef", name: "Steak", category: "Food" },
  { id: "porkchop", name: "Raw Porkchop", category: "Food" },
  { id: "cooked_porkchop", name: "Cooked Porkchop", category: "Food" },
  { id: "chicken", name: "Raw Chicken", category: "Food" },
  { id: "cooked_chicken", name: "Cooked Chicken", category: "Food" },
  { id: "mutton", name: "Raw Mutton", category: "Food" },
  { id: "cooked_mutton", name: "Cooked Mutton", category: "Food" },
  { id: "rabbit", name: "Raw Rabbit", category: "Food" },
  { id: "cooked_rabbit", name: "Cooked Rabbit", category: "Food" },
  { id: "rabbit_stew", name: "Rabbit Stew", category: "Food" },
  { id: "cod", name: "Raw Cod", category: "Food" },
  { id: "cooked_cod", name: "Cooked Cod", category: "Food" },
  { id: "salmon", name: "Raw Salmon", category: "Food" },
  { id: "cooked_salmon", name: "Cooked Salmon", category: "Food" },
  { id: "tropical_fish", name: "Tropical Fish", category: "Food" },
  { id: "mushroom_stew", name: "Mushroom Stew", category: "Food" },
  { id: "beetroot", name: "Beetroot", category: "Food" },
  { id: "beetroot_soup", name: "Beetroot Soup", category: "Food" },
  { id: "carrot", name: "Carrot", category: "Food" },
  { id: "potato", name: "Potato", category: "Food" },
  { id: "baked_potato", name: "Baked Potato", category: "Food" },
  { id: "poisonous_potato", name: "Poisonous Potato", category: "Food" },
  { id: "melon_slice", name: "Melon Slice", category: "Food" },
  { id: "dried_kelp", name: "Dried Kelp", category: "Food" },
  { id: "honey_bottle", name: "Honey Bottle", category: "Food" },
  { id: "suspicious_stew", name: "Suspicious Stew", category: "Food" },

  // ── Combat ──
  { id: "totem_of_undying", name: "Totem of Undying", category: "Combat" },
  { id: "trident", name: "Trident", category: "Weapons" },
  { id: "mace", name: "Mace", category: "Weapons" },
  { id: "crossbow", name: "Crossbow", category: "Weapons" },
  { id: "bow", name: "Bow", category: "Weapons" },
  { id: "arrow", name: "Arrow", category: "Combat" },
  { id: "spectral_arrow", name: "Spectral Arrow", category: "Combat" },
  { id: "tipped_arrow", name: "Tipped Arrow", category: "Combat" },
  { id: "shield", name: "Shield", category: "Combat" },
  { id: "turtle_helmet", name: "Turtle Shell", category: "Armor" },
  { id: "wither_skeleton_skull", name: "Wither Skeleton Skull", category: "Combat" },
  { id: "skeleton_skull", name: "Skeleton Skull", category: "Combat" },
  { id: "zombie_head", name: "Zombie Head", category: "Combat" },
  { id: "creeper_head", name: "Creeper Head", category: "Combat" },
  { id: "player_head", name: "Player Head", category: "Combat" },
  { id: "piglin_head", name: "Piglin Head", category: "Combat" },

  // ── Ocean / Water ──
  { id: "heart_of_the_sea", name: "Heart of the Sea", category: "Ocean" },
  { id: "nautilus_shell", name: "Nautilus Shell", category: "Ocean" },
  { id: "conduit", name: "Conduit", category: "Ocean" },
  { id: "prismarine_shard", name: "Prismarine Shard", category: "Ocean" },
  { id: "prismarine_crystals", name: "Prismarine Crystals", category: "Ocean" },
  { id: "prismarine", name: "Prismarine", category: "Blocks" },
  { id: "prismarine_bricks", name: "Prismarine Bricks", category: "Blocks" },
  { id: "dark_prismarine", name: "Dark Prismarine", category: "Blocks" },
  { id: "sea_lantern", name: "Sea Lantern", category: "Blocks" },
  { id: "sponge", name: "Sponge", category: "Blocks" },
  { id: "wet_sponge", name: "Wet Sponge", category: "Blocks" },
  { id: "kelp", name: "Kelp", category: "Ocean" },
  { id: "dried_kelp_block", name: "Dried Kelp Block", category: "Blocks" },
  { id: "seagrass", name: "Seagrass", category: "Ocean" },
  { id: "sea_pickle", name: "Sea Pickle", category: "Ocean" },
  { id: "ink_sac", name: "Ink Sac", category: "Materials" },
  { id: "glow_ink_sac", name: "Glow Ink Sac", category: "Materials" },

  // ── Animals / Drops ──
  { id: "leather", name: "Leather", category: "Materials" },
  { id: "feather", name: "Feather", category: "Materials" },
  { id: "bone", name: "Bone", category: "Materials" },
  { id: "bone_meal", name: "Bone Meal", category: "Materials" },
  { id: "bone_block", name: "Bone Block", category: "Blocks" },
  { id: "string", name: "String", category: "Materials" },
  { id: "slimeball", name: "Slimeball", category: "Materials" },
  { id: "slime_block", name: "Slime Block", category: "Blocks" },
  { id: "honey_block", name: "Honey Block", category: "Blocks" },
  { id: "honeycomb", name: "Honeycomb", category: "Materials" },
  { id: "honeycomb_block", name: "Honeycomb Block", category: "Blocks" },
  { id: "wool", name: "Wool (White)", category: "Materials" },
  { id: "egg", name: "Egg", category: "Materials" },
  { id: "gunpowder", name: "Gunpowder", category: "Materials" },
  { id: "flint", name: "Flint", category: "Materials" },
  { id: "flint_and_steel", name: "Flint and Steel", category: "Tools" },
  { id: "fire_charge", name: "Fire Charge", category: "Combat" },
  { id: "phantom_membrane", name: "Phantom Membrane", category: "Materials" },
  { id: "scute", name: "Scute", category: "Materials" },
  { id: "armadillo_scute", name: "Armadillo Scute", category: "Materials" },
  { id: "wolf_armor", name: "Wolf Armor", category: "Armor" },
  { id: "breeze_rod", name: "Breeze Rod", category: "Materials" },
  { id: "wind_charge", name: "Wind Charge", category: "Combat" },
  { id: "ominous_trial_key", name: "Ominous Trial Key", category: "Combat" },
  { id: "trial_key", name: "Trial Key", category: "Combat" },
  { id: "heavy_core", name: "Heavy Core", category: "Materials" },
  { id: "ominous_bottle", name: "Ominous Bottle", category: "Combat" },

  // ── Misc tools ──
  { id: "fishing_rod", name: "Fishing Rod", category: "Tools" },
  { id: "carrot_on_a_stick", name: "Carrot on a Stick", category: "Tools" },
  { id: "warped_fungus_on_a_stick", name: "Warped Fungus on a Stick", category: "Tools" },
  { id: "shears", name: "Shears", category: "Tools" },
  { id: "bucket", name: "Bucket", category: "Tools" },
  { id: "water_bucket", name: "Water Bucket", category: "Tools" },
  { id: "lava_bucket", name: "Lava Bucket", category: "Tools" },
  { id: "milk_bucket", name: "Milk Bucket", category: "Tools" },
  { id: "powder_snow_bucket", name: "Powder Snow Bucket", category: "Tools" },
  { id: "axolotl_bucket", name: "Axolotl Bucket", category: "Tools" },
  { id: "compass", name: "Compass", category: "Tools" },
  { id: "recovery_compass", name: "Recovery Compass", category: "Tools" },
  { id: "clock", name: "Clock", category: "Tools" },
  { id: "map", name: "Map", category: "Tools" },
  { id: "filled_map", name: "Filled Map", category: "Tools" },
  { id: "lead", name: "Lead", category: "Tools" },
  { id: "name_tag", name: "Name Tag", category: "Tools" },
  { id: "saddle", name: "Saddle", category: "Tools" },
  { id: "brush", name: "Brush", category: "Tools" },

  // ── Fireworks ──
  { id: "firework_rocket", name: "Firework Rocket", category: "Misc" },
  { id: "firework_star", name: "Firework Star", category: "Misc" },

  // ── Music discs ──
  { id: "music_disc_13", name: "Music Disc (13)", category: "Music" },
  { id: "music_disc_cat", name: "Music Disc (Cat)", category: "Music" },
  { id: "music_disc_blocks", name: "Music Disc (Blocks)", category: "Music" },
  { id: "music_disc_chirp", name: "Music Disc (Chirp)", category: "Music" },
  { id: "music_disc_far", name: "Music Disc (Far)", category: "Music" },
  { id: "music_disc_mall", name: "Music Disc (Mall)", category: "Music" },
  { id: "music_disc_mellohi", name: "Music Disc (Mellohi)", category: "Music" },
  { id: "music_disc_stal", name: "Music Disc (Stal)", category: "Music" },
  { id: "music_disc_strad", name: "Music Disc (Strad)", category: "Music" },
  { id: "music_disc_ward", name: "Music Disc (Ward)", category: "Music" },
  { id: "music_disc_11", name: "Music Disc (11)", category: "Music" },
  { id: "music_disc_wait", name: "Music Disc (Wait)", category: "Music" },
  { id: "music_disc_otherside", name: "Music Disc (Otherside)", category: "Music" },
  { id: "music_disc_5", name: "Music Disc (5)", category: "Music" },
  { id: "music_disc_pigstep", name: "Music Disc (Pigstep)", category: "Music" },
  { id: "music_disc_relic", name: "Music Disc (Relic)", category: "Music" },
  { id: "music_disc_creator", name: "Music Disc (Creator)", category: "Music" },
  { id: "music_disc_creator_music_box", name: "Music Disc (Creator Music Box)", category: "Music" },
  { id: "music_disc_precipice", name: "Music Disc (Precipice)", category: "Music" },
  { id: "disc_fragment_5", name: "Disc Fragment (5)", category: "Music" },

  // ── Dyes ──
  { id: "white_dye", name: "White Dye", category: "Dyes" },
  { id: "orange_dye", name: "Orange Dye", category: "Dyes" },
  { id: "magenta_dye", name: "Magenta Dye", category: "Dyes" },
  { id: "light_blue_dye", name: "Light Blue Dye", category: "Dyes" },
  { id: "yellow_dye", name: "Yellow Dye", category: "Dyes" },
  { id: "lime_dye", name: "Lime Dye", category: "Dyes" },
  { id: "pink_dye", name: "Pink Dye", category: "Dyes" },
  { id: "gray_dye", name: "Gray Dye", category: "Dyes" },
  { id: "light_gray_dye", name: "Light Gray Dye", category: "Dyes" },
  { id: "cyan_dye", name: "Cyan Dye", category: "Dyes" },
  { id: "purple_dye", name: "Purple Dye", category: "Dyes" },
  { id: "blue_dye", name: "Blue Dye", category: "Dyes" },
  { id: "brown_dye", name: "Brown Dye", category: "Dyes" },
  { id: "green_dye", name: "Green Dye", category: "Dyes" },
  { id: "red_dye", name: "Red Dye", category: "Dyes" },
  { id: "black_dye", name: "Black Dye", category: "Dyes" },

  // ── Wool colors ──
  { id: "white_wool", name: "White Wool", category: "Wool" },
  { id: "orange_wool", name: "Orange Wool", category: "Wool" },
  { id: "magenta_wool", name: "Magenta Wool", category: "Wool" },
  { id: "light_blue_wool", name: "Light Blue Wool", category: "Wool" },
  { id: "yellow_wool", name: "Yellow Wool", category: "Wool" },
  { id: "lime_wool", name: "Lime Wool", category: "Wool" },
  { id: "pink_wool", name: "Pink Wool", category: "Wool" },
  { id: "gray_wool", name: "Gray Wool", category: "Wool" },
  { id: "light_gray_wool", name: "Light Gray Wool", category: "Wool" },
  { id: "cyan_wool", name: "Cyan Wool", category: "Wool" },
  { id: "purple_wool", name: "Purple Wool", category: "Wool" },
  { id: "blue_wool", name: "Blue Wool", category: "Wool" },
  { id: "brown_wool", name: "Brown Wool", category: "Wool" },
  { id: "green_wool", name: "Green Wool", category: "Wool" },
  { id: "red_wool", name: "Red Wool", category: "Wool" },
  { id: "black_wool", name: "Black Wool", category: "Wool" },

  // ── Terracotta ──
  { id: "terracotta", name: "Terracotta", category: "Blocks" },
  { id: "white_terracotta", name: "White Terracotta", category: "Blocks" },
  { id: "orange_terracotta", name: "Orange Terracotta", category: "Blocks" },
  { id: "magenta_terracotta", name: "Magenta Terracotta", category: "Blocks" },
  { id: "light_blue_terracotta", name: "Light Blue Terracotta", category: "Blocks" },
  { id: "yellow_terracotta", name: "Yellow Terracotta", category: "Blocks" },
  { id: "lime_terracotta", name: "Lime Terracotta", category: "Blocks" },
  { id: "pink_terracotta", name: "Pink Terracotta", category: "Blocks" },
  { id: "gray_terracotta", name: "Gray Terracotta", category: "Blocks" },
  { id: "light_gray_terracotta", name: "Light Gray Terracotta", category: "Blocks" },
  { id: "cyan_terracotta", name: "Cyan Terracotta", category: "Blocks" },
  { id: "purple_terracotta", name: "Purple Terracotta", category: "Blocks" },
  { id: "blue_terracotta", name: "Blue Terracotta", category: "Blocks" },
  { id: "brown_terracotta", name: "Brown Terracotta", category: "Blocks" },
  { id: "green_terracotta", name: "Green Terracotta", category: "Blocks" },
  { id: "red_terracotta", name: "Red Terracotta", category: "Blocks" },
  { id: "black_terracotta", name: "Black Terracotta", category: "Blocks" },
  { id: "white_glazed_terracotta", name: "White Glazed Terracotta", category: "Blocks" },
  { id: "orange_glazed_terracotta", name: "Orange Glazed Terracotta", category: "Blocks" },
  { id: "magenta_glazed_terracotta", name: "Magenta Glazed Terracotta", category: "Blocks" },
  { id: "light_blue_glazed_terracotta", name: "Light Blue Glazed Terracotta", category: "Blocks" },
  { id: "yellow_glazed_terracotta", name: "Yellow Glazed Terracotta", category: "Blocks" },
  { id: "lime_glazed_terracotta", name: "Lime Glazed Terracotta", category: "Blocks" },
  { id: "pink_glazed_terracotta", name: "Pink Glazed Terracotta", category: "Blocks" },
  { id: "gray_glazed_terracotta", name: "Gray Glazed Terracotta", category: "Blocks" },
  { id: "light_gray_glazed_terracotta", name: "Light Gray Glazed Terracotta", category: "Blocks" },
  { id: "cyan_glazed_terracotta", name: "Cyan Glazed Terracotta", category: "Blocks" },
  { id: "purple_glazed_terracotta", name: "Purple Glazed Terracotta", category: "Blocks" },
  { id: "blue_glazed_terracotta", name: "Blue Glazed Terracotta", category: "Blocks" },
  { id: "brown_glazed_terracotta", name: "Brown Glazed Terracotta", category: "Blocks" },
  { id: "green_glazed_terracotta", name: "Green Glazed Terracotta", category: "Blocks" },
  { id: "red_glazed_terracotta", name: "Red Glazed Terracotta", category: "Blocks" },
  { id: "black_glazed_terracotta", name: "Black Glazed Terracotta", category: "Blocks" },

  // ── Concrete ──
  { id: "white_concrete", name: "White Concrete", category: "Blocks" },
  { id: "orange_concrete", name: "Orange Concrete", category: "Blocks" },
  { id: "magenta_concrete", name: "Magenta Concrete", category: "Blocks" },
  { id: "light_blue_concrete", name: "Light Blue Concrete", category: "Blocks" },
  { id: "yellow_concrete", name: "Yellow Concrete", category: "Blocks" },
  { id: "lime_concrete", name: "Lime Concrete", category: "Blocks" },
  { id: "pink_concrete", name: "Pink Concrete", category: "Blocks" },
  { id: "gray_concrete", name: "Gray Concrete", category: "Blocks" },
  { id: "light_gray_concrete", name: "Light Gray Concrete", category: "Blocks" },
  { id: "cyan_concrete", name: "Cyan Concrete", category: "Blocks" },
  { id: "purple_concrete", name: "Purple Concrete", category: "Blocks" },
  { id: "blue_concrete", name: "Blue Concrete", category: "Blocks" },
  { id: "brown_concrete", name: "Brown Concrete", category: "Blocks" },
  { id: "green_concrete", name: "Green Concrete", category: "Blocks" },
  { id: "red_concrete", name: "Red Concrete", category: "Blocks" },
  { id: "black_concrete", name: "Black Concrete", category: "Blocks" },
  { id: "white_concrete_powder", name: "White Concrete Powder", category: "Blocks" },
  { id: "orange_concrete_powder", name: "Orange Concrete Powder", category: "Blocks" },

  // ── Glass ──
  { id: "glass", name: "Glass", category: "Blocks" },
  { id: "glass_pane", name: "Glass Pane", category: "Blocks" },
  { id: "white_stained_glass", name: "White Stained Glass", category: "Blocks" },
  { id: "orange_stained_glass", name: "Orange Stained Glass", category: "Blocks" },
  { id: "magenta_stained_glass", name: "Magenta Stained Glass", category: "Blocks" },
  { id: "light_blue_stained_glass", name: "Light Blue Stained Glass", category: "Blocks" },
  { id: "yellow_stained_glass", name: "Yellow Stained Glass", category: "Blocks" },
  { id: "lime_stained_glass", name: "Lime Stained Glass", category: "Blocks" },
  { id: "pink_stained_glass", name: "Pink Stained Glass", category: "Blocks" },
  { id: "gray_stained_glass", name: "Gray Stained Glass", category: "Blocks" },
  { id: "light_gray_stained_glass", name: "Light Gray Stained Glass", category: "Blocks" },
  { id: "cyan_stained_glass", name: "Cyan Stained Glass", category: "Blocks" },
  { id: "purple_stained_glass", name: "Purple Stained Glass", category: "Blocks" },
  { id: "blue_stained_glass", name: "Blue Stained Glass", category: "Blocks" },
  { id: "brown_stained_glass", name: "Brown Stained Glass", category: "Blocks" },
  { id: "green_stained_glass", name: "Green Stained Glass", category: "Blocks" },
  { id: "red_stained_glass", name: "Red Stained Glass", category: "Blocks" },
  { id: "black_stained_glass", name: "Black Stained Glass", category: "Blocks" },

  // ── Wood types ──
  { id: "oak_log", name: "Oak Log", category: "Wood" },
  { id: "spruce_log", name: "Spruce Log", category: "Wood" },
  { id: "birch_log", name: "Birch Log", category: "Wood" },
  { id: "jungle_log", name: "Jungle Log", category: "Wood" },
  { id: "acacia_log", name: "Acacia Log", category: "Wood" },
  { id: "dark_oak_log", name: "Dark Oak Log", category: "Wood" },
  { id: "mangrove_log", name: "Mangrove Log", category: "Wood" },
  { id: "cherry_log", name: "Cherry Log", category: "Wood" },
  { id: "bamboo_block", name: "Bamboo Block", category: "Wood" },
  { id: "oak_planks", name: "Oak Planks", category: "Wood" },
  { id: "spruce_planks", name: "Spruce Planks", category: "Wood" },
  { id: "birch_planks", name: "Birch Planks", category: "Wood" },
  { id: "jungle_planks", name: "Jungle Planks", category: "Wood" },
  { id: "acacia_planks", name: "Acacia Planks", category: "Wood" },
  { id: "dark_oak_planks", name: "Dark Oak Planks", category: "Wood" },
  { id: "mangrove_planks", name: "Mangrove Planks", category: "Wood" },
  { id: "cherry_planks", name: "Cherry Planks", category: "Wood" },
  { id: "bamboo_planks", name: "Bamboo Planks", category: "Wood" },

  // ── Stone / Building ──
  { id: "stone", name: "Stone", category: "Blocks" },
  { id: "cobblestone", name: "Cobblestone", category: "Blocks" },
  { id: "stone_bricks", name: "Stone Bricks", category: "Blocks" },
  { id: "cracked_stone_bricks", name: "Cracked Stone Bricks", category: "Blocks" },
  { id: "mossy_stone_bricks", name: "Mossy Stone Bricks", category: "Blocks" },
  { id: "chiseled_stone_bricks", name: "Chiseled Stone Bricks", category: "Blocks" },
  { id: "smooth_stone", name: "Smooth Stone", category: "Blocks" },
  { id: "granite", name: "Granite", category: "Blocks" },
  { id: "polished_granite", name: "Polished Granite", category: "Blocks" },
  { id: "diorite", name: "Diorite", category: "Blocks" },
  { id: "polished_diorite", name: "Polished Diorite", category: "Blocks" },
  { id: "andesite", name: "Andesite", category: "Blocks" },
  { id: "polished_andesite", name: "Polished Andesite", category: "Blocks" },
  { id: "calcite", name: "Calcite", category: "Blocks" },
  { id: "tuff", name: "Tuff", category: "Blocks" },
  { id: "tuff_bricks", name: "Tuff Bricks", category: "Blocks" },
  { id: "deepslate", name: "Deepslate", category: "Blocks" },
  { id: "cobbled_deepslate", name: "Cobbled Deepslate", category: "Blocks" },
  { id: "polished_deepslate", name: "Polished Deepslate", category: "Blocks" },
  { id: "deepslate_bricks", name: "Deepslate Bricks", category: "Blocks" },
  { id: "deepslate_tiles", name: "Deepslate Tiles", category: "Blocks" },
  { id: "reinforced_deepslate", name: "Reinforced Deepslate", category: "Blocks" },
  { id: "mud", name: "Mud", category: "Blocks" },
  { id: "packed_mud", name: "Packed Mud", category: "Blocks" },
  { id: "mud_bricks", name: "Mud Bricks", category: "Blocks" },
  { id: "sandstone", name: "Sandstone", category: "Blocks" },
  { id: "red_sandstone", name: "Red Sandstone", category: "Blocks" },
  { id: "brick", name: "Brick", category: "Materials" },
  { id: "bricks", name: "Bricks", category: "Blocks" },

  // ── Utility blocks ──
  { id: "chest", name: "Chest", category: "Blocks" },
  { id: "trapped_chest", name: "Trapped Chest", category: "Blocks" },
  { id: "barrel", name: "Barrel", category: "Blocks" },
  { id: "crafting_table", name: "Crafting Table", category: "Blocks" },
  { id: "furnace", name: "Furnace", category: "Blocks" },
  { id: "blast_furnace", name: "Blast Furnace", category: "Blocks" },
  { id: "smoker", name: "Smoker", category: "Blocks" },
  { id: "campfire", name: "Campfire", category: "Blocks" },
  { id: "soul_campfire", name: "Soul Campfire", category: "Blocks" },
  { id: "brewing_stand", name: "Brewing Stand", category: "Blocks" },
  { id: "cauldron", name: "Cauldron", category: "Blocks" },
  { id: "enchanting_table", name: "Enchanting Table", category: "Blocks" },
  { id: "ender_chest", name: "Ender Chest", category: "Blocks" },
  { id: "bell", name: "Bell", category: "Blocks" },
  { id: "lantern", name: "Lantern", category: "Blocks" },
  { id: "soul_lantern", name: "Soul Lantern", category: "Blocks" },
  { id: "torch", name: "Torch", category: "Blocks" },
  { id: "soul_torch", name: "Soul Torch", category: "Blocks" },
  { id: "tnt", name: "TNT", category: "Blocks" },
  { id: "loom", name: "Loom", category: "Blocks" },
  { id: "cartography_table", name: "Cartography Table", category: "Blocks" },
  { id: "fletching_table", name: "Fletching Table", category: "Blocks" },
  { id: "smithing_table", name: "Smithing Table", category: "Blocks" },
  { id: "stonecutter", name: "Stonecutter", category: "Blocks" },
  { id: "jukebox", name: "Jukebox", category: "Blocks" },
  { id: "note_block", name: "Note Block", category: "Blocks" },
  { id: "beehive", name: "Beehive", category: "Blocks" },
  { id: "bee_nest", name: "Bee Nest", category: "Blocks" },
  { id: "flower_pot", name: "Flower Pot", category: "Blocks" },
  { id: "decorated_pot", name: "Decorated Pot", category: "Blocks" },
  { id: "item_frame", name: "Item Frame", category: "Blocks" },
  { id: "glow_item_frame", name: "Glow Item Frame", category: "Blocks" },
  { id: "painting", name: "Painting", category: "Blocks" },
  { id: "armor_stand", name: "Armor Stand", category: "Blocks" },
  { id: "lightning_rod", name: "Lightning Rod", category: "Blocks" },
  { id: "scaffolding", name: "Scaffolding", category: "Blocks" },
  { id: "structure_block", name: "Structure Block", category: "Blocks" },
  { id: "command_block", name: "Command Block", category: "Blocks" },
  { id: "trial_spawner", name: "Trial Spawner", category: "Blocks" },
  { id: "vault", name: "Vault", category: "Blocks" },
  { id: "crafter", name: "Crafter", category: "Blocks" },

  // ── Flowers / Plants ──
  { id: "dandelion", name: "Dandelion", category: "Plants" },
  { id: "poppy", name: "Poppy", category: "Plants" },
  { id: "blue_orchid", name: "Blue Orchid", category: "Plants" },
  { id: "allium", name: "Allium", category: "Plants" },
  { id: "azure_bluet", name: "Azure Bluet", category: "Plants" },
  { id: "red_tulip", name: "Red Tulip", category: "Plants" },
  { id: "orange_tulip", name: "Orange Tulip", category: "Plants" },
  { id: "white_tulip", name: "White Tulip", category: "Plants" },
  { id: "pink_tulip", name: "Pink Tulip", category: "Plants" },
  { id: "oxeye_daisy", name: "Oxeye Daisy", category: "Plants" },
  { id: "cornflower", name: "Cornflower", category: "Plants" },
  { id: "lily_of_the_valley", name: "Lily of the Valley", category: "Plants" },
  { id: "wither_rose", name: "Wither Rose", category: "Plants" },
  { id: "torchflower", name: "Torchflower", category: "Plants" },
  { id: "pitcher_plant", name: "Pitcher Plant", category: "Plants" },
  { id: "sunflower", name: "Sunflower", category: "Plants" },
  { id: "lilac", name: "Lilac", category: "Plants" },
  { id: "rose_bush", name: "Rose Bush", category: "Plants" },
  { id: "peony", name: "Peony", category: "Plants" },
  { id: "flowering_azalea", name: "Flowering Azalea", category: "Plants" },
  { id: "azalea", name: "Azalea", category: "Plants" },
  { id: "spore_blossom", name: "Spore Blossom", category: "Plants" },
  { id: "mangrove_propagule", name: "Mangrove Propagule", category: "Plants" },
  { id: "cherry_sapling", name: "Cherry Sapling", category: "Plants" },
  { id: "bamboo", name: "Bamboo", category: "Plants" },
  { id: "cactus", name: "Cactus", category: "Plants" },
  { id: "sugar_cane", name: "Sugar Cane", category: "Plants" },
  { id: "pumpkin", name: "Pumpkin", category: "Plants" },
  { id: "melon", name: "Melon", category: "Plants" },
  { id: "brown_mushroom", name: "Brown Mushroom", category: "Plants" },
  { id: "red_mushroom", name: "Red Mushroom", category: "Plants" },

  // ── Spawn Eggs ──
  { id: "bat_spawn_egg", name: "Bat Spawn Egg", category: "Spawn Eggs" },
  { id: "bee_spawn_egg", name: "Bee Spawn Egg", category: "Spawn Eggs" },
  { id: "blaze_spawn_egg", name: "Blaze Spawn Egg", category: "Spawn Eggs" },
  { id: "bogged_spawn_egg", name: "Bogged Spawn Egg", category: "Spawn Eggs" },
  { id: "breeze_spawn_egg", name: "Breeze Spawn Egg", category: "Spawn Eggs" },
  { id: "cat_spawn_egg", name: "Cat Spawn Egg", category: "Spawn Eggs" },
  { id: "cave_spider_spawn_egg", name: "Cave Spider Spawn Egg", category: "Spawn Eggs" },
  { id: "chicken_spawn_egg", name: "Chicken Spawn Egg", category: "Spawn Eggs" },
  { id: "cod_spawn_egg", name: "Cod Spawn Egg", category: "Spawn Eggs" },
  { id: "cow_spawn_egg", name: "Cow Spawn Egg", category: "Spawn Eggs" },
  { id: "creeper_spawn_egg", name: "Creeper Spawn Egg", category: "Spawn Eggs" },
  { id: "dolphin_spawn_egg", name: "Dolphin Spawn Egg", category: "Spawn Eggs" },
  { id: "donkey_spawn_egg", name: "Donkey Spawn Egg", category: "Spawn Eggs" },
  { id: "drowned_spawn_egg", name: "Drowned Spawn Egg", category: "Spawn Eggs" },
  { id: "elder_guardian_spawn_egg", name: "Elder Guardian Spawn Egg", category: "Spawn Eggs" },
  { id: "enderman_spawn_egg", name: "Enderman Spawn Egg", category: "Spawn Eggs" },
  { id: "endermite_spawn_egg", name: "Endermite Spawn Egg", category: "Spawn Eggs" },
  { id: "evoker_spawn_egg", name: "Evoker Spawn Egg", category: "Spawn Eggs" },
  { id: "fox_spawn_egg", name: "Fox Spawn Egg", category: "Spawn Eggs" },
  { id: "frog_spawn_egg", name: "Frog Spawn Egg", category: "Spawn Eggs" },
  { id: "ghast_spawn_egg", name: "Ghast Spawn Egg", category: "Spawn Eggs" },
  { id: "glow_squid_spawn_egg", name: "Glow Squid Spawn Egg", category: "Spawn Eggs" },
  { id: "goat_spawn_egg", name: "Goat Spawn Egg", category: "Spawn Eggs" },
  { id: "guardian_spawn_egg", name: "Guardian Spawn Egg", category: "Spawn Eggs" },
  { id: "hoglin_spawn_egg", name: "Hoglin Spawn Egg", category: "Spawn Eggs" },
  { id: "horse_spawn_egg", name: "Horse Spawn Egg", category: "Spawn Eggs" },
  { id: "husk_spawn_egg", name: "Husk Spawn Egg", category: "Spawn Eggs" },
  { id: "llama_spawn_egg", name: "Llama Spawn Egg", category: "Spawn Eggs" },
  { id: "magma_cube_spawn_egg", name: "Magma Cube Spawn Egg", category: "Spawn Eggs" },
  { id: "mooshroom_spawn_egg", name: "Mooshroom Spawn Egg", category: "Spawn Eggs" },
  { id: "mule_spawn_egg", name: "Mule Spawn Egg", category: "Spawn Eggs" },
  { id: "ocelot_spawn_egg", name: "Ocelot Spawn Egg", category: "Spawn Eggs" },
  { id: "panda_spawn_egg", name: "Panda Spawn Egg", category: "Spawn Eggs" },
  { id: "parrot_spawn_egg", name: "Parrot Spawn Egg", category: "Spawn Eggs" },
  { id: "phantom_spawn_egg", name: "Phantom Spawn Egg", category: "Spawn Eggs" },
  { id: "pig_spawn_egg", name: "Pig Spawn Egg", category: "Spawn Eggs" },
  { id: "piglin_spawn_egg", name: "Piglin Spawn Egg", category: "Spawn Eggs" },
  { id: "piglin_brute_spawn_egg", name: "Piglin Brute Spawn Egg", category: "Spawn Eggs" },
  { id: "pillager_spawn_egg", name: "Pillager Spawn Egg", category: "Spawn Eggs" },
  { id: "polar_bear_spawn_egg", name: "Polar Bear Spawn Egg", category: "Spawn Eggs" },
  { id: "pufferfish_spawn_egg", name: "Pufferfish Spawn Egg", category: "Spawn Eggs" },
  { id: "rabbit_spawn_egg", name: "Rabbit Spawn Egg", category: "Spawn Eggs" },
  { id: "ravager_spawn_egg", name: "Ravager Spawn Egg", category: "Spawn Eggs" },
  { id: "salmon_spawn_egg", name: "Salmon Spawn Egg", category: "Spawn Eggs" },
  { id: "sheep_spawn_egg", name: "Sheep Spawn Egg", category: "Spawn Eggs" },
  { id: "shulker_spawn_egg", name: "Shulker Spawn Egg", category: "Spawn Eggs" },
  { id: "silverfish_spawn_egg", name: "Silverfish Spawn Egg", category: "Spawn Eggs" },
  { id: "skeleton_spawn_egg", name: "Skeleton Spawn Egg", category: "Spawn Eggs" },
  { id: "skeleton_horse_spawn_egg", name: "Skeleton Horse Spawn Egg", category: "Spawn Eggs" },
  { id: "slime_spawn_egg", name: "Slime Spawn Egg", category: "Spawn Eggs" },
  { id: "sniffer_spawn_egg", name: "Sniffer Spawn Egg", category: "Spawn Eggs" },
  { id: "snow_golem_spawn_egg", name: "Snow Golem Spawn Egg", category: "Spawn Eggs" },
  { id: "spider_spawn_egg", name: "Spider Spawn Egg", category: "Spawn Eggs" },
  { id: "squid_spawn_egg", name: "Squid Spawn Egg", category: "Spawn Eggs" },
  { id: "stray_spawn_egg", name: "Stray Spawn Egg", category: "Spawn Eggs" },
  { id: "strider_spawn_egg", name: "Strider Spawn Egg", category: "Spawn Eggs" },
  { id: "tadpole_spawn_egg", name: "Tadpole Spawn Egg", category: "Spawn Eggs" },
  { id: "trader_llama_spawn_egg", name: "Trader Llama Spawn Egg", category: "Spawn Eggs" },
  { id: "tropical_fish_spawn_egg", name: "Tropical Fish Spawn Egg", category: "Spawn Eggs" },
  { id: "turtle_spawn_egg", name: "Turtle Spawn Egg", category: "Spawn Eggs" },
  { id: "vex_spawn_egg", name: "Vex Spawn Egg", category: "Spawn Eggs" },
  { id: "villager_spawn_egg", name: "Villager Spawn Egg", category: "Spawn Eggs" },
  { id: "vindicator_spawn_egg", name: "Vindicator Spawn Egg", category: "Spawn Eggs" },
  { id: "wandering_trader_spawn_egg", name: "Wandering Trader Spawn Egg", category: "Spawn Eggs" },
  { id: "warden_spawn_egg", name: "Warden Spawn Egg", category: "Spawn Eggs" },
  { id: "witch_spawn_egg", name: "Witch Spawn Egg", category: "Spawn Eggs" },
  { id: "wither_skeleton_spawn_egg", name: "Wither Skeleton Spawn Egg", category: "Spawn Eggs" },
  { id: "wolf_spawn_egg", name: "Wolf Spawn Egg", category: "Spawn Eggs" },
  { id: "zoglin_spawn_egg", name: "Zoglin Spawn Egg", category: "Spawn Eggs" },
  { id: "zombie_spawn_egg", name: "Zombie Spawn Egg", category: "Spawn Eggs" },
  { id: "zombie_horse_spawn_egg", name: "Zombie Horse Spawn Egg", category: "Spawn Eggs" },
  { id: "zombie_villager_spawn_egg", name: "Zombie Villager Spawn Egg", category: "Spawn Eggs" },
  { id: "zombified_piglin_spawn_egg", name: "Zombified Piglin Spawn Egg", category: "Spawn Eggs" },
  { id: "armadillo_spawn_egg", name: "Armadillo Spawn Egg", category: "Spawn Eggs" },
];

export function searchMcItems(query: string): McItem[] {
  const q = query.toLowerCase().trim();
  if (!q) return MC_ITEMS.slice(0, 12);
  return MC_ITEMS.filter(
    (item) =>
      item.name.toLowerCase().includes(q) ||
      item.id.toLowerCase().includes(q) ||
      item.category.toLowerCase().includes(q),
  ).slice(0, 20);
}
